// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bfd/v1/bfd.proto

package bfdv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionState represents the BFD session state (RFC 5880 Section 4.1, Section 6.2).
type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_ADMIN_DOWN  SessionState = 1
	SessionState_SESSION_STATE_DOWN        SessionState = 2
	SessionState_SESSION_STATE_INIT        SessionState = 3
	SessionState_SESSION_STATE_UP          SessionState = 4
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_ADMIN_DOWN",
		2: "SESSION_STATE_DOWN",
		3: "SESSION_STATE_INIT",
		4: "SESSION_STATE_UP",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_ADMIN_DOWN":  1,
		"SESSION_STATE_DOWN":        2,
		"SESSION_STATE_INIT":        3,
		"SESSION_STATE_UP":          4,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{0}
}

// DiagnosticCode represents the BFD diagnostic code (RFC 5880 Section 4.1).
type DiagnosticCode int32

const (
	DiagnosticCode_DIAGNOSTIC_CODE_UNSPECIFIED              DiagnosticCode = 0
	DiagnosticCode_DIAGNOSTIC_CODE_NONE                     DiagnosticCode = 1
	DiagnosticCode_DIAGNOSTIC_CODE_CONTROL_TIME_EXPIRED     DiagnosticCode = 2
	DiagnosticCode_DIAGNOSTIC_CODE_ECHO_FAILED              DiagnosticCode = 3
	DiagnosticCode_DIAGNOSTIC_CODE_NEIGHBOR_DOWN            DiagnosticCode = 4
	DiagnosticCode_DIAGNOSTIC_CODE_FORWARDING_RESET         DiagnosticCode = 5
	DiagnosticCode_DIAGNOSTIC_CODE_PATH_DOWN                DiagnosticCode = 6
	DiagnosticCode_DIAGNOSTIC_CODE_CONCAT_PATH_DOWN         DiagnosticCode = 7
	DiagnosticCode_DIAGNOSTIC_CODE_ADMIN_DOWN               DiagnosticCode = 8
	DiagnosticCode_DIAGNOSTIC_CODE_REVERSE_CONCAT_PATH_DOWN DiagnosticCode = 9
)

// Enum value maps for DiagnosticCode.
var (
	DiagnosticCode_name = map[int32]string{
		0: "DIAGNOSTIC_CODE_UNSPECIFIED",
		1: "DIAGNOSTIC_CODE_NONE",
		2: "DIAGNOSTIC_CODE_CONTROL_TIME_EXPIRED",
		3: "DIAGNOSTIC_CODE_ECHO_FAILED",
		4: "DIAGNOSTIC_CODE_NEIGHBOR_DOWN",
		5: "DIAGNOSTIC_CODE_FORWARDING_RESET",
		6: "DIAGNOSTIC_CODE_PATH_DOWN",
		7: "DIAGNOSTIC_CODE_CONCAT_PATH_DOWN",
		8: "DIAGNOSTIC_CODE_ADMIN_DOWN",
		9: "DIAGNOSTIC_CODE_REVERSE_CONCAT_PATH_DOWN",
	}
	DiagnosticCode_value = map[string]int32{
		"DIAGNOSTIC_CODE_UNSPECIFIED":              0,
		"DIAGNOSTIC_CODE_NONE":                     1,
		"DIAGNOSTIC_CODE_CONTROL_TIME_EXPIRED":     2,
		"DIAGNOSTIC_CODE_ECHO_FAILED":              3,
		"DIAGNOSTIC_CODE_NEIGHBOR_DOWN":            4,
		"DIAGNOSTIC_CODE_FORWARDING_RESET":         5,
		"DIAGNOSTIC_CODE_PATH_DOWN":                6,
		"DIAGNOSTIC_CODE_CONCAT_PATH_DOWN":         7,
		"DIAGNOSTIC_CODE_ADMIN_DOWN":               8,
		"DIAGNOSTIC_CODE_REVERSE_CONCAT_PATH_DOWN": 9,
	}
)

func (x DiagnosticCode) Enum() *DiagnosticCode {
	p := new(DiagnosticCode)
	*p = x
	return p
}

func (x DiagnosticCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticCode) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[1].Descriptor()
}

func (DiagnosticCode) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[1]
}

func (x DiagnosticCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticCode.Descriptor instead.
func (DiagnosticCode) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{1}
}

// AuthenticationType identifies the BFD authentication mechanism (RFC 5880 Section 4.1).
type AuthenticationType int32

const (
	AuthenticationType_AUTHENTICATION_TYPE_UNSPECIFIED           AuthenticationType = 0
	AuthenticationType_AUTHENTICATION_TYPE_NONE                  AuthenticationType = 1
	AuthenticationType_AUTHENTICATION_TYPE_SIMPLE_PASSWORD       AuthenticationType = 2
	AuthenticationType_AUTHENTICATION_TYPE_KEYED_MD5             AuthenticationType = 3
	AuthenticationType_AUTHENTICATION_TYPE_METICULOUS_KEYED_MD5  AuthenticationType = 4
	AuthenticationType_AUTHENTICATION_TYPE_KEYED_SHA1            AuthenticationType = 5
	AuthenticationType_AUTHENTICATION_TYPE_METICULOUS_KEYED_SHA1 AuthenticationType = 6
)

// Enum value maps for AuthenticationType.
var (
	AuthenticationType_name = map[int32]string{
		0: "AUTHENTICATION_TYPE_UNSPECIFIED",
		1: "AUTHENTICATION_TYPE_NONE",
		2: "AUTHENTICATION_TYPE_SIMPLE_PASSWORD",
		3: "AUTHENTICATION_TYPE_KEYED_MD5",
		4: "AUTHENTICATION_TYPE_METICULOUS_KEYED_MD5",
		5: "AUTHENTICATION_TYPE_KEYED_SHA1",
		6: "AUTHENTICATION_TYPE_METICULOUS_KEYED_SHA1",
	}
	AuthenticationType_value = map[string]int32{
		"AUTHENTICATION_TYPE_UNSPECIFIED":           0,
		"AUTHENTICATION_TYPE_NONE":                  1,
		"AUTHENTICATION_TYPE_SIMPLE_PASSWORD":       2,
		"AUTHENTICATION_TYPE_KEYED_MD5":             3,
		"AUTHENTICATION_TYPE_METICULOUS_KEYED_MD5":  4,
		"AUTHENTICATION_TYPE_KEYED_SHA1":            5,
		"AUTHENTICATION_TYPE_METICULOUS_KEYED_SHA1": 6,
	}
)

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[2].Descriptor()
}

func (AuthenticationType) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[2]
}

func (x AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationType.Descriptor instead.
func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{2}
}

// SessionType distinguishes single-hop from multi-hop BFD sessions.
type SessionType int32

const (
	SessionType_SESSION_TYPE_UNSPECIFIED SessionType = 0
	// Single-hop: RFC 5881, port 3784, TTL=255 both ways.
	SessionType_SESSION_TYPE_SINGLE_HOP SessionType = 1
	// Multi-hop: RFC 5883, port 4784, TX TTL=255, RX TTL>=254.
	SessionType_SESSION_TYPE_MULTI_HOP SessionType = 2
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0: "SESSION_TYPE_UNSPECIFIED",
		1: "SESSION_TYPE_SINGLE_HOP",
		2: "SESSION_TYPE_MULTI_HOP",
	}
	SessionType_value = map[string]int32{
		"SESSION_TYPE_UNSPECIFIED": 0,
		"SESSION_TYPE_SINGLE_HOP":  1,
		"SESSION_TYPE_MULTI_HOP":   2,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[3].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[3]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{3}
}

// EventType classifies the session event.
type WatchSessionEventsResponse_EventType int32

const (
	WatchSessionEventsResponse_EVENT_TYPE_UNSPECIFIED     WatchSessionEventsResponse_EventType = 0
	WatchSessionEventsResponse_EVENT_TYPE_STATE_CHANGE    WatchSessionEventsResponse_EventType = 1
	WatchSessionEventsResponse_EVENT_TYPE_SESSION_ADDED   WatchSessionEventsResponse_EventType = 2
	WatchSessionEventsResponse_EVENT_TYPE_SESSION_DELETED WatchSessionEventsResponse_EventType = 3
)

// Enum value maps for WatchSessionEventsResponse_EventType.
var (
	WatchSessionEventsResponse_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_STATE_CHANGE",
		2: "EVENT_TYPE_SESSION_ADDED",
		3: "EVENT_TYPE_SESSION_DELETED",
	}
	WatchSessionEventsResponse_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_STATE_CHANGE":    1,
		"EVENT_TYPE_SESSION_ADDED":   2,
		"EVENT_TYPE_SESSION_DELETED": 3,
	}
)

func (x WatchSessionEventsResponse_EventType) Enum() *WatchSessionEventsResponse_EventType {
	p := new(WatchSessionEventsResponse_EventType)
	*p = x
	return p
}

func (x WatchSessionEventsResponse_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchSessionEventsResponse_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[4].Descriptor()
}

func (WatchSessionEventsResponse_EventType) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[4]
}

func (x WatchSessionEventsResponse_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchSessionEventsResponse_EventType.Descriptor instead.
func (WatchSessionEventsResponse_EventType) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{11, 0}
}

// BfdSession represents the full state of a BFD session.
type BfdSession struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress           string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	LocalAddress          string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	InterfaceName         string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Type                  SessionType            `protobuf:"varint,4,opt,name=type,proto3,enum=bfd.v1.SessionType" json:"type,omitempty"`
	LocalState            SessionState           `protobuf:"varint,5,opt,name=local_state,json=localState,proto3,enum=bfd.v1.SessionState" json:"local_state,omitempty"`
	RemoteState           SessionState           `protobuf:"varint,6,opt,name=remote_state,json=remoteState,proto3,enum=bfd.v1.SessionState" json:"remote_state,omitempty"`
	LocalDiagnostic       DiagnosticCode         `protobuf:"varint,7,opt,name=local_diagnostic,json=localDiagnostic,proto3,enum=bfd.v1.DiagnosticCode" json:"local_diagnostic,omitempty"`
	LocalDiscriminator    uint32                 `protobuf:"varint,8,opt,name=local_discriminator,json=localDiscriminator,proto3" json:"local_discriminator,omitempty"`
	RemoteDiscriminator   uint32                 `protobuf:"varint,9,opt,name=remote_discriminator,json=remoteDiscriminator,proto3" json:"remote_discriminator,omitempty"`
	DesiredMinTxInterval  *durationpb.Duration   `protobuf:"bytes,10,opt,name=desired_min_tx_interval,json=desiredMinTxInterval,proto3" json:"desired_min_tx_interval,omitempty"`
	RequiredMinRxInterval *durationpb.Duration   `protobuf:"bytes,11,opt,name=required_min_rx_interval,json=requiredMinRxInterval,proto3" json:"required_min_rx_interval,omitempty"`
	RemoteMinRxInterval   *durationpb.Duration   `protobuf:"bytes,12,opt,name=remote_min_rx_interval,json=remoteMinRxInterval,proto3" json:"remote_min_rx_interval,omitempty"`
	DetectMultiplier      uint32                 `protobuf:"varint,13,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	NegotiatedTxInterval  *durationpb.Duration   `protobuf:"bytes,14,opt,name=negotiated_tx_interval,json=negotiatedTxInterval,proto3" json:"negotiated_tx_interval,omitempty"`
	DetectionTime         *durationpb.Duration   `protobuf:"bytes,15,opt,name=detection_time,json=detectionTime,proto3" json:"detection_time,omitempty"`
	AuthType              AuthenticationType     `protobuf:"varint,16,opt,name=auth_type,json=authType,proto3,enum=bfd.v1.AuthenticationType" json:"auth_type,omitempty"`
	LastStateChange       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_state_change,json=lastStateChange,proto3" json:"last_state_change,omitempty"`
	LastPacketReceived    *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=last_packet_received,json=lastPacketReceived,proto3" json:"last_packet_received,omitempty"`
	Counters              *SessionCounters       `protobuf:"bytes,19,opt,name=counters,proto3" json:"counters,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BfdSession) Reset() {
	*x = BfdSession{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BfdSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdSession) ProtoMessage() {}

func (x *BfdSession) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdSession.ProtoReflect.Descriptor instead.
func (*BfdSession) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{0}
}

func (x *BfdSession) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *BfdSession) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *BfdSession) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *BfdSession) GetType() SessionType {
	if x != nil {
		return x.Type
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *BfdSession) GetLocalState() SessionState {
	if x != nil {
		return x.LocalState
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *BfdSession) GetRemoteState() SessionState {
	if x != nil {
		return x.RemoteState
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *BfdSession) GetLocalDiagnostic() DiagnosticCode {
	if x != nil {
		return x.LocalDiagnostic
	}
	return DiagnosticCode_DIAGNOSTIC_CODE_UNSPECIFIED
}

func (x *BfdSession) GetLocalDiscriminator() uint32 {
	if x != nil {
		return x.LocalDiscriminator
	}
	return 0
}

func (x *BfdSession) GetRemoteDiscriminator() uint32 {
	if x != nil {
		return x.RemoteDiscriminator
	}
	return 0
}

func (x *BfdSession) GetDesiredMinTxInterval() *durationpb.Duration {
	if x != nil {
		return x.DesiredMinTxInterval
	}
	return nil
}

func (x *BfdSession) GetRequiredMinRxInterval() *durationpb.Duration {
	if x != nil {
		return x.RequiredMinRxInterval
	}
	return nil
}

func (x *BfdSession) GetRemoteMinRxInterval() *durationpb.Duration {
	if x != nil {
		return x.RemoteMinRxInterval
	}
	return nil
}

func (x *BfdSession) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *BfdSession) GetNegotiatedTxInterval() *durationpb.Duration {
	if x != nil {
		return x.NegotiatedTxInterval
	}
	return nil
}

func (x *BfdSession) GetDetectionTime() *durationpb.Duration {
	if x != nil {
		return x.DetectionTime
	}
	return nil
}

func (x *BfdSession) GetAuthType() AuthenticationType {
	if x != nil {
		return x.AuthType
	}
	return AuthenticationType_AUTHENTICATION_TYPE_UNSPECIFIED
}

func (x *BfdSession) GetLastStateChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStateChange
	}
	return nil
}

func (x *BfdSession) GetLastPacketReceived() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPacketReceived
	}
	return nil
}

func (x *BfdSession) GetCounters() *SessionCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

// SessionCounters contains packet and state transition counters for a session.
type SessionCounters struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PacketsSent      uint64                 `protobuf:"varint,1,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsReceived  uint64                 `protobuf:"varint,2,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsDropped   uint64                 `protobuf:"varint,3,opt,name=packets_dropped,json=packetsDropped,proto3" json:"packets_dropped,omitempty"`
	StateTransitions uint64                 `protobuf:"varint,4,opt,name=state_transitions,json=stateTransitions,proto3" json:"state_transitions,omitempty"`
	AuthFailures     uint64                 `protobuf:"varint,5,opt,name=auth_failures,json=authFailures,proto3" json:"auth_failures,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionCounters) Reset() {
	*x = SessionCounters{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCounters) ProtoMessage() {}

func (x *SessionCounters) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCounters.ProtoReflect.Descriptor instead.
func (*SessionCounters) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{1}
}

func (x *SessionCounters) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *SessionCounters) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *SessionCounters) GetPacketsDropped() uint64 {
	if x != nil {
		return x.PacketsDropped
	}
	return 0
}

func (x *SessionCounters) GetStateTransitions() uint64 {
	if x != nil {
		return x.StateTransitions
	}
	return 0
}

func (x *SessionCounters) GetAuthFailures() uint64 {
	if x != nil {
		return x.AuthFailures
	}
	return 0
}

// AddSessionRequest creates a new BFD session.
type AddSessionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress           string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	LocalAddress          string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	InterfaceName         string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Type                  SessionType            `protobuf:"varint,4,opt,name=type,proto3,enum=bfd.v1.SessionType" json:"type,omitempty"`
	DesiredMinTxInterval  *durationpb.Duration   `protobuf:"bytes,5,opt,name=desired_min_tx_interval,json=desiredMinTxInterval,proto3" json:"desired_min_tx_interval,omitempty"`
	RequiredMinRxInterval *durationpb.Duration   `protobuf:"bytes,6,opt,name=required_min_rx_interval,json=requiredMinRxInterval,proto3" json:"required_min_rx_interval,omitempty"`
	DetectMultiplier      uint32                 `protobuf:"varint,7,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	AuthType              AuthenticationType     `protobuf:"varint,8,opt,name=auth_type,json=authType,proto3,enum=bfd.v1.AuthenticationType" json:"auth_type,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddSessionRequest) Reset() {
	*x = AddSessionRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionRequest) ProtoMessage() {}

func (x *AddSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionRequest.ProtoReflect.Descriptor instead.
func (*AddSessionRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{2}
}

func (x *AddSessionRequest) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *AddSessionRequest) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *AddSessionRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *AddSessionRequest) GetType() SessionType {
	if x != nil {
		return x.Type
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *AddSessionRequest) GetDesiredMinTxInterval() *durationpb.Duration {
	if x != nil {
		return x.DesiredMinTxInterval
	}
	return nil
}

func (x *AddSessionRequest) GetRequiredMinRxInterval() *durationpb.Duration {
	if x != nil {
		return x.RequiredMinRxInterval
	}
	return nil
}

func (x *AddSessionRequest) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *AddSessionRequest) GetAuthType() AuthenticationType {
	if x != nil {
		return x.AuthType
	}
	return AuthenticationType_AUTHENTICATION_TYPE_UNSPECIFIED
}

// AddSessionResponse returns the newly created session.
type AddSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *BfdSession            `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionResponse) Reset() {
	*x = AddSessionResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionResponse) ProtoMessage() {}

func (x *AddSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionResponse.ProtoReflect.Descriptor instead.
func (*AddSessionResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{3}
}

func (x *AddSessionResponse) GetSession() *BfdSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// DeleteSessionRequest removes a BFD session by its local discriminator.
type DeleteSessionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LocalDiscriminator uint32                 `protobuf:"varint,1,opt,name=local_discriminator,json=localDiscriminator,proto3" json:"local_discriminator,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSessionRequest) GetLocalDiscriminator() uint32 {
	if x != nil {
		return x.LocalDiscriminator
	}
	return 0
}

// DeleteSessionResponse is empty on success.
type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{5}
}

// ListSessionsRequest retrieves all active BFD sessions.
type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{6}
}

// ListSessionsResponse contains all active BFD sessions.
type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*BfdSession          `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{7}
}

func (x *ListSessionsResponse) GetSessions() []*BfdSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// GetSessionRequest retrieves a single BFD session by discriminator or peer address.
type GetSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetSessionRequest_LocalDiscriminator
	//	*GetSessionRequest_PeerAddress
	Identifier    isGetSessionRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionRequest) GetIdentifier() isGetSessionRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetSessionRequest) GetLocalDiscriminator() uint32 {
	if x != nil {
		if x, ok := x.Identifier.(*GetSessionRequest_LocalDiscriminator); ok {
			return x.LocalDiscriminator
		}
	}
	return 0
}

func (x *GetSessionRequest) GetPeerAddress() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetSessionRequest_PeerAddress); ok {
			return x.PeerAddress
		}
	}
	return ""
}

type isGetSessionRequest_Identifier interface {
	isGetSessionRequest_Identifier()
}

type GetSessionRequest_LocalDiscriminator struct {
	LocalDiscriminator uint32 `protobuf:"varint,1,opt,name=local_discriminator,json=localDiscriminator,proto3,oneof"`
}

type GetSessionRequest_PeerAddress struct {
	PeerAddress string `protobuf:"bytes,2,opt,name=peer_address,json=peerAddress,proto3,oneof"`
}

func (*GetSessionRequest_LocalDiscriminator) isGetSessionRequest_Identifier() {}

func (*GetSessionRequest_PeerAddress) isGetSessionRequest_Identifier() {}

// GetSessionResponse returns the requested BFD session.
type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *BfdSession            `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionResponse) GetSession() *BfdSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// WatchSessionEventsRequest starts a server-side stream of BFD session events.
type WatchSessionEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, send current state of all sessions first, then stream changes.
	// Pattern from GoBGP: gobgp monitor --current.
	IncludeCurrent bool `protobuf:"varint,1,opt,name=include_current,json=includeCurrent,proto3" json:"include_current,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchSessionEventsRequest) Reset() {
	*x = WatchSessionEventsRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionEventsRequest) ProtoMessage() {}

func (x *WatchSessionEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchSessionEventsRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{10}
}

func (x *WatchSessionEventsRequest) GetIncludeCurrent() bool {
	if x != nil {
		return x.IncludeCurrent
	}
	return false
}

// WatchSessionEventsResponse represents a BFD session lifecycle event
// streamed from WatchSessionEvents RPC.
type WatchSessionEventsResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          WatchSessionEventsResponse_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=bfd.v1.WatchSessionEventsResponse_EventType" json:"type,omitempty"`
	Session       *BfdSession                          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	PreviousState SessionState                         `protobuf:"varint,3,opt,name=previous_state,json=previousState,proto3,enum=bfd.v1.SessionState" json:"previous_state,omitempty"`
	Timestamp     *timestamppb.Timestamp               `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSessionEventsResponse) Reset() {
	*x = WatchSessionEventsResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionEventsResponse) ProtoMessage() {}

func (x *WatchSessionEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionEventsResponse.ProtoReflect.Descriptor instead.
func (*WatchSessionEventsResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{11}
}

func (x *WatchSessionEventsResponse) GetType() WatchSessionEventsResponse_EventType {
	if x != nil {
		return x.Type
	}
	return WatchSessionEventsResponse_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchSessionEventsResponse) GetSession() *BfdSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *WatchSessionEventsResponse) GetPreviousState() SessionState {
	if x != nil {
		return x.PreviousState
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *WatchSessionEventsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_bfd_v1_bfd_proto protoreflect.FileDescriptor

const file_bfd_v1_bfd_proto_rawDesc = "" +
	"\n" +
	"\x10bfd/v1/bfd.proto\x12\x06bfd.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\t\n" +
	"\n" +
	"BfdSession\x12*\n" +
	"\fpeer_address\x18\x01 \x01(\tB\a\xbaH\x04r\x02p\x01R\vpeerAddress\x12,\n" +
	"\rlocal_address\x18\x02 \x01(\tB\a\xbaH\x04r\x02p\x01R\flocalAddress\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.bfd.v1.SessionTypeR\x04type\x125\n" +
	"\vlocal_state\x18\x05 \x01(\x0e2\x14.bfd.v1.SessionStateR\n" +
	"localState\x127\n" +
	"\fremote_state\x18\x06 \x01(\x0e2\x14.bfd.v1.SessionStateR\vremoteState\x12A\n" +
	"\x10local_diagnostic\x18\a \x01(\x0e2\x16.bfd.v1.DiagnosticCodeR\x0flocalDiagnostic\x12/\n" +
	"\x13local_discriminator\x18\b \x01(\rR\x12localDiscriminator\x121\n" +
	"\x14remote_discriminator\x18\t \x01(\rR\x13remoteDiscriminator\x12P\n" +
	"\x17desired_min_tx_interval\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x14desiredMinTxInterval\x12R\n" +
	"\x18required_min_rx_interval\x18\v \x01(\v2\x19.google.protobuf.DurationR\x15requiredMinRxInterval\x12N\n" +
	"\x16remote_min_rx_interval\x18\f \x01(\v2\x19.google.protobuf.DurationR\x13remoteMinRxInterval\x124\n" +
	"\x11detect_multiplier\x18\r \x01(\rB\a\xbaH\x04*\x02(\x01R\x10detectMultiplier\x12O\n" +
	"\x16negotiated_tx_interval\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\x14negotiatedTxInterval\x12@\n" +
	"\x0edetection_time\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\rdetectionTime\x127\n" +
	"\tauth_type\x18\x10 \x01(\x0e2\x1a.bfd.v1.AuthenticationTypeR\bauthType\x12F\n" +
	"\x11last_state_change\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastStateChange\x12L\n" +
	"\x14last_packet_received\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastPacketReceived\x123\n" +
	"\bcounters\x18\x13 \x01(\v2\x17.bfd.v1.SessionCountersR\bcounters\"\xda\x01\n" +
	"\x0fSessionCounters\x12!\n" +
	"\fpackets_sent\x18\x01 \x01(\x04R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\x02 \x01(\x04R\x0fpacketsReceived\x12'\n" +
	"\x0fpackets_dropped\x18\x03 \x01(\x04R\x0epacketsDropped\x12+\n" +
	"\x11state_transitions\x18\x04 \x01(\x04R\x10stateTransitions\x12#\n" +
	"\rauth_failures\x18\x05 \x01(\x04R\fauthFailures\"\xd2\x03\n" +
	"\x11AddSessionRequest\x12*\n" +
	"\fpeer_address\x18\x01 \x01(\tB\a\xbaH\x04r\x02p\x01R\vpeerAddress\x12,\n" +
	"\rlocal_address\x18\x02 \x01(\tB\a\xbaH\x04r\x02p\x01R\flocalAddress\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.bfd.v1.SessionTypeR\x04type\x12P\n" +
	"\x17desired_min_tx_interval\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x14desiredMinTxInterval\x12R\n" +
	"\x18required_min_rx_interval\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x15requiredMinRxInterval\x124\n" +
	"\x11detect_multiplier\x18\a \x01(\rB\a\xbaH\x04*\x02(\x01R\x10detectMultiplier\x127\n" +
	"\tauth_type\x18\b \x01(\x0e2\x1a.bfd.v1.AuthenticationTypeR\bauthType\"B\n" +
	"\x12AddSessionResponse\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.bfd.v1.BfdSessionR\asession\"G\n" +
	"\x14DeleteSessionRequest\x12/\n" +
	"\x13local_discriminator\x18\x01 \x01(\rR\x12localDiscriminator\"\x17\n" +
	"\x15DeleteSessionResponse\"\x15\n" +
	"\x13ListSessionsRequest\"F\n" +
	"\x14ListSessionsResponse\x12.\n" +
	"\bsessions\x18\x01 \x03(\v2\x12.bfd.v1.BfdSessionR\bsessions\"y\n" +
	"\x11GetSessionRequest\x121\n" +
	"\x13local_discriminator\x18\x01 \x01(\rH\x00R\x12localDiscriminator\x12#\n" +
	"\fpeer_address\x18\x02 \x01(\tH\x00R\vpeerAddressB\f\n" +
	"\n" +
	"identifier\"B\n" +
	"\x12GetSessionResponse\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.bfd.v1.BfdSessionR\asession\"D\n" +
	"\x19WatchSessionEventsRequest\x12'\n" +
	"\x0finclude_current\x18\x01 \x01(\bR\x0eincludeCurrent\"\x88\x03\n" +
	"\x1aWatchSessionEventsResponse\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.bfd.v1.WatchSessionEventsResponse.EventTypeR\x04type\x12,\n" +
	"\asession\x18\x02 \x01(\v2\x12.bfd.v1.BfdSessionR\asession\x12;\n" +
	"\x0eprevious_state\x18\x03 \x01(\x0e2\x14.bfd.v1.SessionStateR\rpreviousState\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_STATE_CHANGE\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_SESSION_ADDED\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_SESSION_DELETED\x10\x03*\x91\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SESSION_STATE_ADMIN_DOWN\x10\x01\x12\x16\n" +
	"\x12SESSION_STATE_DOWN\x10\x02\x12\x16\n" +
	"\x12SESSION_STATE_INIT\x10\x03\x12\x14\n" +
	"\x10SESSION_STATE_UP\x10\x04*\xf2\x02\n" +
	"\x0eDiagnosticCode\x12\x1f\n" +
	"\x1bDIAGNOSTIC_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DIAGNOSTIC_CODE_NONE\x10\x01\x12(\n" +
	"$DIAGNOSTIC_CODE_CONTROL_TIME_EXPIRED\x10\x02\x12\x1f\n" +
	"\x1bDIAGNOSTIC_CODE_ECHO_FAILED\x10\x03\x12!\n" +
	"\x1dDIAGNOSTIC_CODE_NEIGHBOR_DOWN\x10\x04\x12$\n" +
	" DIAGNOSTIC_CODE_FORWARDING_RESET\x10\x05\x12\x1d\n" +
	"\x19DIAGNOSTIC_CODE_PATH_DOWN\x10\x06\x12$\n" +
	" DIAGNOSTIC_CODE_CONCAT_PATH_DOWN\x10\a\x12\x1e\n" +
	"\x1aDIAGNOSTIC_CODE_ADMIN_DOWN\x10\b\x12,\n" +
	"(DIAGNOSTIC_CODE_REVERSE_CONCAT_PATH_DOWN\x10\t*\xa4\x02\n" +
	"\x12AuthenticationType\x12#\n" +
	"\x1fAUTHENTICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AUTHENTICATION_TYPE_NONE\x10\x01\x12'\n" +
	"#AUTHENTICATION_TYPE_SIMPLE_PASSWORD\x10\x02\x12!\n" +
	"\x1dAUTHENTICATION_TYPE_KEYED_MD5\x10\x03\x12,\n" +
	"(AUTHENTICATION_TYPE_METICULOUS_KEYED_MD5\x10\x04\x12\"\n" +
	"\x1eAUTHENTICATION_TYPE_KEYED_SHA1\x10\x05\x12-\n" +
	")AUTHENTICATION_TYPE_METICULOUS_KEYED_SHA1\x10\x06*d\n" +
	"\vSessionType\x12\x1c\n" +
	"\x18SESSION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SESSION_TYPE_SINGLE_HOP\x10\x01\x12\x1a\n" +
	"\x16SESSION_TYPE_MULTI_HOP\x10\x022\x8e\x03\n" +
	"\n" +
	"BfdService\x12C\n" +
	"\n" +
	"AddSession\x12\x19.bfd.v1.AddSessionRequest\x1a\x1a.bfd.v1.AddSessionResponse\x12L\n" +
	"\rDeleteSession\x12\x1c.bfd.v1.DeleteSessionRequest\x1a\x1d.bfd.v1.DeleteSessionResponse\x12I\n" +
	"\fListSessions\x12\x1b.bfd.v1.ListSessionsRequest\x1a\x1c.bfd.v1.ListSessionsResponse\x12C\n" +
	"\n" +
	"GetSession\x12\x19.bfd.v1.GetSessionRequest\x1a\x1a.bfd.v1.GetSessionResponse\x12]\n" +
	"\x12WatchSessionEvents\x12!.bfd.v1.WatchSessionEventsRequest\x1a\".bfd.v1.WatchSessionEventsResponse0\x01B\x82\x01\n" +
	"\n" +
	"com.bfd.v1B\bBfdProtoP\x01Z1github.com/dantte-lp/gobfd/pkg/bfdpb/bfd/v1;bfdv1\xa2\x02\x03BXX\xaa\x02\x06Bfd.V1\xca\x02\x06Bfd\\V1\xe2\x02\x12Bfd\\V1\\GPBMetadata\xea\x02\aBfd::V1b\x06proto3"

var (
	file_bfd_v1_bfd_proto_rawDescOnce sync.Once
	file_bfd_v1_bfd_proto_rawDescData []byte
)

func file_bfd_v1_bfd_proto_rawDescGZIP() []byte {
	file_bfd_v1_bfd_proto_rawDescOnce.Do(func() {
		file_bfd_v1_bfd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bfd_v1_bfd_proto_rawDesc), len(file_bfd_v1_bfd_proto_rawDesc)))
	})
	return file_bfd_v1_bfd_proto_rawDescData
}

var file_bfd_v1_bfd_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_bfd_v1_bfd_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_bfd_v1_bfd_proto_goTypes = []any{
	(SessionState)(0),                         // 0: bfd.v1.SessionState
	(DiagnosticCode)(0),                       // 1: bfd.v1.DiagnosticCode
	(AuthenticationType)(0),                   // 2: bfd.v1.AuthenticationType
	(SessionType)(0),                          // 3: bfd.v1.SessionType
	(WatchSessionEventsResponse_EventType)(0), // 4: bfd.v1.WatchSessionEventsResponse.EventType
	(*BfdSession)(nil),                        // 5: bfd.v1.BfdSession
	(*SessionCounters)(nil),                   // 6: bfd.v1.SessionCounters
	(*AddSessionRequest)(nil),                 // 7: bfd.v1.AddSessionRequest
	(*AddSessionResponse)(nil),                // 8: bfd.v1.AddSessionResponse
	(*DeleteSessionRequest)(nil),              // 9: bfd.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),             // 10: bfd.v1.DeleteSessionResponse
	(*ListSessionsRequest)(nil),               // 11: bfd.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),              // 12: bfd.v1.ListSessionsResponse
	(*GetSessionRequest)(nil),                 // 13: bfd.v1.GetSessionRequest
	(*GetSessionResponse)(nil),                // 14: bfd.v1.GetSessionResponse
	(*WatchSessionEventsRequest)(nil),         // 15: bfd.v1.WatchSessionEventsRequest
	(*WatchSessionEventsResponse)(nil),        // 16: bfd.v1.WatchSessionEventsResponse
	(*durationpb.Duration)(nil),               // 17: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),             // 18: google.protobuf.Timestamp
}
var file_bfd_v1_bfd_proto_depIdxs = []int32{
	3,  // 0: bfd.v1.BfdSession.type:type_name -> bfd.v1.SessionType
	0,  // 1: bfd.v1.BfdSession.local_state:type_name -> bfd.v1.SessionState
	0,  // 2: bfd.v1.BfdSession.remote_state:type_name -> bfd.v1.SessionState
	1,  // 3: bfd.v1.BfdSession.local_diagnostic:type_name -> bfd.v1.DiagnosticCode
	17, // 4: bfd.v1.BfdSession.desired_min_tx_interval:type_name -> google.protobuf.Duration
	17, // 5: bfd.v1.BfdSession.required_min_rx_interval:type_name -> google.protobuf.Duration
	17, // 6: bfd.v1.BfdSession.remote_min_rx_interval:type_name -> google.protobuf.Duration
	17, // 7: bfd.v1.BfdSession.negotiated_tx_interval:type_name -> google.protobuf.Duration
	17, // 8: bfd.v1.BfdSession.detection_time:type_name -> google.protobuf.Duration
	2,  // 9: bfd.v1.BfdSession.auth_type:type_name -> bfd.v1.AuthenticationType
	18, // 10: bfd.v1.BfdSession.last_state_change:type_name -> google.protobuf.Timestamp
	18, // 11: bfd.v1.BfdSession.last_packet_received:type_name -> google.protobuf.Timestamp
	6,  // 12: bfd.v1.BfdSession.counters:type_name -> bfd.v1.SessionCounters
	3,  // 13: bfd.v1.AddSessionRequest.type:type_name -> bfd.v1.SessionType
	17, // 14: bfd.v1.AddSessionRequest.desired_min_tx_interval:type_name -> google.protobuf.Duration
	17, // 15: bfd.v1.AddSessionRequest.required_min_rx_interval:type_name -> google.protobuf.Duration
	2,  // 16: bfd.v1.AddSessionRequest.auth_type:type_name -> bfd.v1.AuthenticationType
	5,  // 17: bfd.v1.AddSessionResponse.session:type_name -> bfd.v1.BfdSession
	5,  // 18: bfd.v1.ListSessionsResponse.sessions:type_name -> bfd.v1.BfdSession
	5,  // 19: bfd.v1.GetSessionResponse.session:type_name -> bfd.v1.BfdSession
	4,  // 20: bfd.v1.WatchSessionEventsResponse.type:type_name -> bfd.v1.WatchSessionEventsResponse.EventType
	5,  // 21: bfd.v1.WatchSessionEventsResponse.session:type_name -> bfd.v1.BfdSession
	0,  // 22: bfd.v1.WatchSessionEventsResponse.previous_state:type_name -> bfd.v1.SessionState
	18, // 23: bfd.v1.WatchSessionEventsResponse.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 24: bfd.v1.BfdService.AddSession:input_type -> bfd.v1.AddSessionRequest
	9,  // 25: bfd.v1.BfdService.DeleteSession:input_type -> bfd.v1.DeleteSessionRequest
	11, // 26: bfd.v1.BfdService.ListSessions:input_type -> bfd.v1.ListSessionsRequest
	13, // 27: bfd.v1.BfdService.GetSession:input_type -> bfd.v1.GetSessionRequest
	15, // 28: bfd.v1.BfdService.WatchSessionEvents:input_type -> bfd.v1.WatchSessionEventsRequest
	8,  // 29: bfd.v1.BfdService.AddSession:output_type -> bfd.v1.AddSessionResponse
	10, // 30: bfd.v1.BfdService.DeleteSession:output_type -> bfd.v1.DeleteSessionResponse
	12, // 31: bfd.v1.BfdService.ListSessions:output_type -> bfd.v1.ListSessionsResponse
	14, // 32: bfd.v1.BfdService.GetSession:output_type -> bfd.v1.GetSessionResponse
	16, // 33: bfd.v1.BfdService.WatchSessionEvents:output_type -> bfd.v1.WatchSessionEventsResponse
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_bfd_v1_bfd_proto_init() }
func file_bfd_v1_bfd_proto_init() {
	if File_bfd_v1_bfd_proto != nil {
		return
	}
	file_bfd_v1_bfd_proto_msgTypes[8].OneofWrappers = []any{
		(*GetSessionRequest_LocalDiscriminator)(nil),
		(*GetSessionRequest_PeerAddress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bfd_v1_bfd_proto_rawDesc), len(file_bfd_v1_bfd_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bfd_v1_bfd_proto_goTypes,
		DependencyIndexes: file_bfd_v1_bfd_proto_depIdxs,
		EnumInfos:         file_bfd_v1_bfd_proto_enumTypes,
		MessageInfos:      file_bfd_v1_bfd_proto_msgTypes,
	}.Build()
	File_bfd_v1_bfd_proto = out.File
	file_bfd_v1_bfd_proto_goTypes = nil
	file_bfd_v1_bfd_proto_depIdxs = nil
}
