// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bfd/v1/bfd.proto

package bfdv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionState represents the BFD session state (RFC 5880 Section 4.1, Section 6.2).
type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_ADMIN_DOWN  SessionState = 1
	SessionState_SESSION_STATE_DOWN        SessionState = 2
	SessionState_SESSION_STATE_INIT        SessionState = 3
	SessionState_SESSION_STATE_UP          SessionState = 4
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_ADMIN_DOWN",
		2: "SESSION_STATE_DOWN",
		3: "SESSION_STATE_INIT",
		4: "SESSION_STATE_UP",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_ADMIN_DOWN":  1,
		"SESSION_STATE_DOWN":        2,
		"SESSION_STATE_INIT":        3,
		"SESSION_STATE_UP":          4,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{0}
}

// DiagnosticCode represents the BFD diagnostic code (RFC 5880 Section 4.1).
type DiagnosticCode int32

const (
	DiagnosticCode_DIAGNOSTIC_CODE_UNSPECIFIED              DiagnosticCode = 0
	DiagnosticCode_DIAGNOSTIC_CODE_NONE                     DiagnosticCode = 1
	DiagnosticCode_DIAGNOSTIC_CODE_CONTROL_TIME_EXPIRED     DiagnosticCode = 2
	DiagnosticCode_DIAGNOSTIC_CODE_ECHO_FAILED              DiagnosticCode = 3
	DiagnosticCode_DIAGNOSTIC_CODE_NEIGHBOR_DOWN            DiagnosticCode = 4
	DiagnosticCode_DIAGNOSTIC_CODE_FORWARDING_RESET         DiagnosticCode = 5
	DiagnosticCode_DIAGNOSTIC_CODE_PATH_DOWN                DiagnosticCode = 6
	DiagnosticCode_DIAGNOSTIC_CODE_CONCAT_PATH_DOWN         DiagnosticCode = 7
	DiagnosticCode_DIAGNOSTIC_CODE_ADMIN_DOWN               DiagnosticCode = 8
	DiagnosticCode_DIAGNOSTIC_CODE_REVERSE_CONCAT_PATH_DOWN DiagnosticCode = 9
)

// Enum value maps for DiagnosticCode.
var (
	DiagnosticCode_name = map[int32]string{
		0: "DIAGNOSTIC_CODE_UNSPECIFIED",
		1: "DIAGNOSTIC_CODE_NONE",
		2: "DIAGNOSTIC_CODE_CONTROL_TIME_EXPIRED",
		3: "DIAGNOSTIC_CODE_ECHO_FAILED",
		4: "DIAGNOSTIC_CODE_NEIGHBOR_DOWN",
		5: "DIAGNOSTIC_CODE_FORWARDING_RESET",
		6: "DIAGNOSTIC_CODE_PATH_DOWN",
		7: "DIAGNOSTIC_CODE_CONCAT_PATH_DOWN",
		8: "DIAGNOSTIC_CODE_ADMIN_DOWN",
		9: "DIAGNOSTIC_CODE_REVERSE_CONCAT_PATH_DOWN",
	}
	DiagnosticCode_value = map[string]int32{
		"DIAGNOSTIC_CODE_UNSPECIFIED":              0,
		"DIAGNOSTIC_CODE_NONE":                     1,
		"DIAGNOSTIC_CODE_CONTROL_TIME_EXPIRED":     2,
		"DIAGNOSTIC_CODE_ECHO_FAILED":              3,
		"DIAGNOSTIC_CODE_NEIGHBOR_DOWN":            4,
		"DIAGNOSTIC_CODE_FORWARDING_RESET":         5,
		"DIAGNOSTIC_CODE_PATH_DOWN":                6,
		"DIAGNOSTIC_CODE_CONCAT_PATH_DOWN":         7,
		"DIAGNOSTIC_CODE_ADMIN_DOWN":               8,
		"DIAGNOSTIC_CODE_REVERSE_CONCAT_PATH_DOWN": 9,
	}
)

func (x DiagnosticCode) Enum() *DiagnosticCode {
	p := new(DiagnosticCode)
	*p = x
	return p
}

func (x DiagnosticCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiagnosticCode) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[1].Descriptor()
}

func (DiagnosticCode) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[1]
}

func (x DiagnosticCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiagnosticCode.Descriptor instead.
func (DiagnosticCode) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{1}
}

// AuthenticationType identifies the BFD authentication mechanism (RFC 5880 Section 4.1).
type AuthenticationType int32

const (
	AuthenticationType_AUTHENTICATION_TYPE_UNSPECIFIED           AuthenticationType = 0
	AuthenticationType_AUTHENTICATION_TYPE_NONE                  AuthenticationType = 1
	AuthenticationType_AUTHENTICATION_TYPE_SIMPLE_PASSWORD       AuthenticationType = 2
	AuthenticationType_AUTHENTICATION_TYPE_KEYED_MD5             AuthenticationType = 3
	AuthenticationType_AUTHENTICATION_TYPE_METICULOUS_KEYED_MD5  AuthenticationType = 4
	AuthenticationType_AUTHENTICATION_TYPE_KEYED_SHA1            AuthenticationType = 5
	AuthenticationType_AUTHENTICATION_TYPE_METICULOUS_KEYED_SHA1 AuthenticationType = 6
)

// Enum value maps for AuthenticationType.
var (
	AuthenticationType_name = map[int32]string{
		0: "AUTHENTICATION_TYPE_UNSPECIFIED",
		1: "AUTHENTICATION_TYPE_NONE",
		2: "AUTHENTICATION_TYPE_SIMPLE_PASSWORD",
		3: "AUTHENTICATION_TYPE_KEYED_MD5",
		4: "AUTHENTICATION_TYPE_METICULOUS_KEYED_MD5",
		5: "AUTHENTICATION_TYPE_KEYED_SHA1",
		6: "AUTHENTICATION_TYPE_METICULOUS_KEYED_SHA1",
	}
	AuthenticationType_value = map[string]int32{
		"AUTHENTICATION_TYPE_UNSPECIFIED":           0,
		"AUTHENTICATION_TYPE_NONE":                  1,
		"AUTHENTICATION_TYPE_SIMPLE_PASSWORD":       2,
		"AUTHENTICATION_TYPE_KEYED_MD5":             3,
		"AUTHENTICATION_TYPE_METICULOUS_KEYED_MD5":  4,
		"AUTHENTICATION_TYPE_KEYED_SHA1":            5,
		"AUTHENTICATION_TYPE_METICULOUS_KEYED_SHA1": 6,
	}
)

func (x AuthenticationType) Enum() *AuthenticationType {
	p := new(AuthenticationType)
	*p = x
	return p
}

func (x AuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[2].Descriptor()
}

func (AuthenticationType) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[2]
}

func (x AuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticationType.Descriptor instead.
func (AuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{2}
}

// SessionType identifies the BFD session family.
type SessionType int32

const (
	SessionType_SESSION_TYPE_UNSPECIFIED SessionType = 0
	// Single-hop: RFC 5881, port 3784, TTL=255 both ways.
	SessionType_SESSION_TYPE_SINGLE_HOP SessionType = 1
	// Multi-hop: RFC 5883, port 4784, TX TTL=255, RX TTL>=254.
	SessionType_SESSION_TYPE_MULTI_HOP SessionType = 2
	// Echo: RFC 9747 unaffiliated BFD echo sessions.
	SessionType_SESSION_TYPE_ECHO SessionType = 3
	// Micro-BFD: RFC 7130 per-member LAG sessions, UDP port 6784.
	SessionType_SESSION_TYPE_MICRO_BFD SessionType = 4
	// VXLAN: RFC 8971 BFD over VXLAN Management VNI.
	SessionType_SESSION_TYPE_VXLAN SessionType = 5
	// Geneve: RFC 9521 BFD over Geneve tunnels.
	SessionType_SESSION_TYPE_GENEVE SessionType = 6
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0: "SESSION_TYPE_UNSPECIFIED",
		1: "SESSION_TYPE_SINGLE_HOP",
		2: "SESSION_TYPE_MULTI_HOP",
		3: "SESSION_TYPE_ECHO",
		4: "SESSION_TYPE_MICRO_BFD",
		5: "SESSION_TYPE_VXLAN",
		6: "SESSION_TYPE_GENEVE",
	}
	SessionType_value = map[string]int32{
		"SESSION_TYPE_UNSPECIFIED": 0,
		"SESSION_TYPE_SINGLE_HOP":  1,
		"SESSION_TYPE_MULTI_HOP":   2,
		"SESSION_TYPE_ECHO":        3,
		"SESSION_TYPE_MICRO_BFD":   4,
		"SESSION_TYPE_VXLAN":       5,
		"SESSION_TYPE_GENEVE":      6,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[3].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[3]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{3}
}

// EventType classifies the session event.
type WatchSessionEventsResponse_EventType int32

const (
	WatchSessionEventsResponse_EVENT_TYPE_UNSPECIFIED     WatchSessionEventsResponse_EventType = 0
	WatchSessionEventsResponse_EVENT_TYPE_STATE_CHANGE    WatchSessionEventsResponse_EventType = 1
	WatchSessionEventsResponse_EVENT_TYPE_SESSION_ADDED   WatchSessionEventsResponse_EventType = 2
	WatchSessionEventsResponse_EVENT_TYPE_SESSION_DELETED WatchSessionEventsResponse_EventType = 3
)

// Enum value maps for WatchSessionEventsResponse_EventType.
var (
	WatchSessionEventsResponse_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_STATE_CHANGE",
		2: "EVENT_TYPE_SESSION_ADDED",
		3: "EVENT_TYPE_SESSION_DELETED",
	}
	WatchSessionEventsResponse_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":     0,
		"EVENT_TYPE_STATE_CHANGE":    1,
		"EVENT_TYPE_SESSION_ADDED":   2,
		"EVENT_TYPE_SESSION_DELETED": 3,
	}
)

func (x WatchSessionEventsResponse_EventType) Enum() *WatchSessionEventsResponse_EventType {
	p := new(WatchSessionEventsResponse_EventType)
	*p = x
	return p
}

func (x WatchSessionEventsResponse_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchSessionEventsResponse_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_bfd_v1_bfd_proto_enumTypes[4].Descriptor()
}

func (WatchSessionEventsResponse_EventType) Type() protoreflect.EnumType {
	return &file_bfd_v1_bfd_proto_enumTypes[4]
}

func (x WatchSessionEventsResponse_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchSessionEventsResponse_EventType.Descriptor instead.
func (WatchSessionEventsResponse_EventType) EnumDescriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{11, 0}
}

// BfdSession represents the full state of a BFD session.
type BfdSession struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress           string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	LocalAddress          string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	InterfaceName         string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Type                  SessionType            `protobuf:"varint,4,opt,name=type,proto3,enum=bfd.v1.SessionType" json:"type,omitempty"`
	LocalState            SessionState           `protobuf:"varint,5,opt,name=local_state,json=localState,proto3,enum=bfd.v1.SessionState" json:"local_state,omitempty"`
	RemoteState           SessionState           `protobuf:"varint,6,opt,name=remote_state,json=remoteState,proto3,enum=bfd.v1.SessionState" json:"remote_state,omitempty"`
	LocalDiagnostic       DiagnosticCode         `protobuf:"varint,7,opt,name=local_diagnostic,json=localDiagnostic,proto3,enum=bfd.v1.DiagnosticCode" json:"local_diagnostic,omitempty"`
	LocalDiscriminator    uint32                 `protobuf:"varint,8,opt,name=local_discriminator,json=localDiscriminator,proto3" json:"local_discriminator,omitempty"`
	RemoteDiscriminator   uint32                 `protobuf:"varint,9,opt,name=remote_discriminator,json=remoteDiscriminator,proto3" json:"remote_discriminator,omitempty"`
	DesiredMinTxInterval  *durationpb.Duration   `protobuf:"bytes,10,opt,name=desired_min_tx_interval,json=desiredMinTxInterval,proto3" json:"desired_min_tx_interval,omitempty"`
	RequiredMinRxInterval *durationpb.Duration   `protobuf:"bytes,11,opt,name=required_min_rx_interval,json=requiredMinRxInterval,proto3" json:"required_min_rx_interval,omitempty"`
	RemoteMinRxInterval   *durationpb.Duration   `protobuf:"bytes,12,opt,name=remote_min_rx_interval,json=remoteMinRxInterval,proto3" json:"remote_min_rx_interval,omitempty"`
	DetectMultiplier      uint32                 `protobuf:"varint,13,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	NegotiatedTxInterval  *durationpb.Duration   `protobuf:"bytes,14,opt,name=negotiated_tx_interval,json=negotiatedTxInterval,proto3" json:"negotiated_tx_interval,omitempty"`
	DetectionTime         *durationpb.Duration   `protobuf:"bytes,15,opt,name=detection_time,json=detectionTime,proto3" json:"detection_time,omitempty"`
	AuthType              AuthenticationType     `protobuf:"varint,16,opt,name=auth_type,json=authType,proto3,enum=bfd.v1.AuthenticationType" json:"auth_type,omitempty"`
	LastStateChange       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_state_change,json=lastStateChange,proto3" json:"last_state_change,omitempty"`
	LastPacketReceived    *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=last_packet_received,json=lastPacketReceived,proto3" json:"last_packet_received,omitempty"`
	Counters              *SessionCounters       `protobuf:"bytes,19,opt,name=counters,proto3" json:"counters,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BfdSession) Reset() {
	*x = BfdSession{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BfdSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BfdSession) ProtoMessage() {}

func (x *BfdSession) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BfdSession.ProtoReflect.Descriptor instead.
func (*BfdSession) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{0}
}

func (x *BfdSession) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *BfdSession) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *BfdSession) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *BfdSession) GetType() SessionType {
	if x != nil {
		return x.Type
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *BfdSession) GetLocalState() SessionState {
	if x != nil {
		return x.LocalState
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *BfdSession) GetRemoteState() SessionState {
	if x != nil {
		return x.RemoteState
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *BfdSession) GetLocalDiagnostic() DiagnosticCode {
	if x != nil {
		return x.LocalDiagnostic
	}
	return DiagnosticCode_DIAGNOSTIC_CODE_UNSPECIFIED
}

func (x *BfdSession) GetLocalDiscriminator() uint32 {
	if x != nil {
		return x.LocalDiscriminator
	}
	return 0
}

func (x *BfdSession) GetRemoteDiscriminator() uint32 {
	if x != nil {
		return x.RemoteDiscriminator
	}
	return 0
}

func (x *BfdSession) GetDesiredMinTxInterval() *durationpb.Duration {
	if x != nil {
		return x.DesiredMinTxInterval
	}
	return nil
}

func (x *BfdSession) GetRequiredMinRxInterval() *durationpb.Duration {
	if x != nil {
		return x.RequiredMinRxInterval
	}
	return nil
}

func (x *BfdSession) GetRemoteMinRxInterval() *durationpb.Duration {
	if x != nil {
		return x.RemoteMinRxInterval
	}
	return nil
}

func (x *BfdSession) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *BfdSession) GetNegotiatedTxInterval() *durationpb.Duration {
	if x != nil {
		return x.NegotiatedTxInterval
	}
	return nil
}

func (x *BfdSession) GetDetectionTime() *durationpb.Duration {
	if x != nil {
		return x.DetectionTime
	}
	return nil
}

func (x *BfdSession) GetAuthType() AuthenticationType {
	if x != nil {
		return x.AuthType
	}
	return AuthenticationType_AUTHENTICATION_TYPE_UNSPECIFIED
}

func (x *BfdSession) GetLastStateChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStateChange
	}
	return nil
}

func (x *BfdSession) GetLastPacketReceived() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPacketReceived
	}
	return nil
}

func (x *BfdSession) GetCounters() *SessionCounters {
	if x != nil {
		return x.Counters
	}
	return nil
}

// SessionCounters contains packet and state transition counters for a session.
type SessionCounters struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PacketsSent      uint64                 `protobuf:"varint,1,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	PacketsReceived  uint64                 `protobuf:"varint,2,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	PacketsDropped   uint64                 `protobuf:"varint,3,opt,name=packets_dropped,json=packetsDropped,proto3" json:"packets_dropped,omitempty"`
	StateTransitions uint64                 `protobuf:"varint,4,opt,name=state_transitions,json=stateTransitions,proto3" json:"state_transitions,omitempty"`
	AuthFailures     uint64                 `protobuf:"varint,5,opt,name=auth_failures,json=authFailures,proto3" json:"auth_failures,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionCounters) Reset() {
	*x = SessionCounters{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCounters) ProtoMessage() {}

func (x *SessionCounters) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCounters.ProtoReflect.Descriptor instead.
func (*SessionCounters) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{1}
}

func (x *SessionCounters) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *SessionCounters) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *SessionCounters) GetPacketsDropped() uint64 {
	if x != nil {
		return x.PacketsDropped
	}
	return 0
}

func (x *SessionCounters) GetStateTransitions() uint64 {
	if x != nil {
		return x.StateTransitions
	}
	return 0
}

func (x *SessionCounters) GetAuthFailures() uint64 {
	if x != nil {
		return x.AuthFailures
	}
	return 0
}

// AddSessionRequest creates a new BFD session.
type AddSessionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress           string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	LocalAddress          string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	InterfaceName         string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Type                  SessionType            `protobuf:"varint,4,opt,name=type,proto3,enum=bfd.v1.SessionType" json:"type,omitempty"`
	DesiredMinTxInterval  *durationpb.Duration   `protobuf:"bytes,5,opt,name=desired_min_tx_interval,json=desiredMinTxInterval,proto3" json:"desired_min_tx_interval,omitempty"`
	RequiredMinRxInterval *durationpb.Duration   `protobuf:"bytes,6,opt,name=required_min_rx_interval,json=requiredMinRxInterval,proto3" json:"required_min_rx_interval,omitempty"`
	DetectMultiplier      uint32                 `protobuf:"varint,7,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	AuthType              AuthenticationType     `protobuf:"varint,8,opt,name=auth_type,json=authType,proto3,enum=bfd.v1.AuthenticationType" json:"auth_type,omitempty"`
	AuthKeyId             uint32                 `protobuf:"varint,9,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	AuthSecret            []byte                 `protobuf:"bytes,10,opt,name=auth_secret,json=authSecret,proto3" json:"auth_secret,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddSessionRequest) Reset() {
	*x = AddSessionRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionRequest) ProtoMessage() {}

func (x *AddSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionRequest.ProtoReflect.Descriptor instead.
func (*AddSessionRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{2}
}

func (x *AddSessionRequest) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *AddSessionRequest) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *AddSessionRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *AddSessionRequest) GetType() SessionType {
	if x != nil {
		return x.Type
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *AddSessionRequest) GetDesiredMinTxInterval() *durationpb.Duration {
	if x != nil {
		return x.DesiredMinTxInterval
	}
	return nil
}

func (x *AddSessionRequest) GetRequiredMinRxInterval() *durationpb.Duration {
	if x != nil {
		return x.RequiredMinRxInterval
	}
	return nil
}

func (x *AddSessionRequest) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *AddSessionRequest) GetAuthType() AuthenticationType {
	if x != nil {
		return x.AuthType
	}
	return AuthenticationType_AUTHENTICATION_TYPE_UNSPECIFIED
}

func (x *AddSessionRequest) GetAuthKeyId() uint32 {
	if x != nil {
		return x.AuthKeyId
	}
	return 0
}

func (x *AddSessionRequest) GetAuthSecret() []byte {
	if x != nil {
		return x.AuthSecret
	}
	return nil
}

// AddSessionResponse returns the newly created session.
type AddSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *BfdSession            `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSessionResponse) Reset() {
	*x = AddSessionResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSessionResponse) ProtoMessage() {}

func (x *AddSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSessionResponse.ProtoReflect.Descriptor instead.
func (*AddSessionResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{3}
}

func (x *AddSessionResponse) GetSession() *BfdSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// DeleteSessionRequest removes a BFD session by its local discriminator.
type DeleteSessionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LocalDiscriminator uint32                 `protobuf:"varint,1,opt,name=local_discriminator,json=localDiscriminator,proto3" json:"local_discriminator,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteSessionRequest) GetLocalDiscriminator() uint32 {
	if x != nil {
		return x.LocalDiscriminator
	}
	return 0
}

// DeleteSessionResponse is empty on success.
type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{5}
}

// ListSessionsRequest retrieves all active BFD sessions.
type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{6}
}

// ListSessionsResponse contains all active BFD sessions.
type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*BfdSession          `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{7}
}

func (x *ListSessionsResponse) GetSessions() []*BfdSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// GetSessionRequest retrieves a single BFD session by discriminator or peer address.
type GetSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetSessionRequest_LocalDiscriminator
	//	*GetSessionRequest_PeerAddress
	Identifier    isGetSessionRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionRequest) GetIdentifier() isGetSessionRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetSessionRequest) GetLocalDiscriminator() uint32 {
	if x != nil {
		if x, ok := x.Identifier.(*GetSessionRequest_LocalDiscriminator); ok {
			return x.LocalDiscriminator
		}
	}
	return 0
}

func (x *GetSessionRequest) GetPeerAddress() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetSessionRequest_PeerAddress); ok {
			return x.PeerAddress
		}
	}
	return ""
}

type isGetSessionRequest_Identifier interface {
	isGetSessionRequest_Identifier()
}

type GetSessionRequest_LocalDiscriminator struct {
	LocalDiscriminator uint32 `protobuf:"varint,1,opt,name=local_discriminator,json=localDiscriminator,proto3,oneof"`
}

type GetSessionRequest_PeerAddress struct {
	PeerAddress string `protobuf:"bytes,2,opt,name=peer_address,json=peerAddress,proto3,oneof"`
}

func (*GetSessionRequest_LocalDiscriminator) isGetSessionRequest_Identifier() {}

func (*GetSessionRequest_PeerAddress) isGetSessionRequest_Identifier() {}

// GetSessionResponse returns the requested BFD session.
type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *BfdSession            `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionResponse) GetSession() *BfdSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// WatchSessionEventsRequest starts a server-side stream of BFD session events.
type WatchSessionEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, send current state of all sessions first, then stream changes.
	// Pattern from GoBGP: gobgp monitor --current.
	IncludeCurrent bool `protobuf:"varint,1,opt,name=include_current,json=includeCurrent,proto3" json:"include_current,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchSessionEventsRequest) Reset() {
	*x = WatchSessionEventsRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionEventsRequest) ProtoMessage() {}

func (x *WatchSessionEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchSessionEventsRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{10}
}

func (x *WatchSessionEventsRequest) GetIncludeCurrent() bool {
	if x != nil {
		return x.IncludeCurrent
	}
	return false
}

// WatchSessionEventsResponse represents a BFD session lifecycle event
// streamed from WatchSessionEvents RPC.
type WatchSessionEventsResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          WatchSessionEventsResponse_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=bfd.v1.WatchSessionEventsResponse_EventType" json:"type,omitempty"`
	Session       *BfdSession                          `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	PreviousState SessionState                         `protobuf:"varint,3,opt,name=previous_state,json=previousState,proto3,enum=bfd.v1.SessionState" json:"previous_state,omitempty"`
	Timestamp     *timestamppb.Timestamp               `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSessionEventsResponse) Reset() {
	*x = WatchSessionEventsResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionEventsResponse) ProtoMessage() {}

func (x *WatchSessionEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionEventsResponse.ProtoReflect.Descriptor instead.
func (*WatchSessionEventsResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{11}
}

func (x *WatchSessionEventsResponse) GetType() WatchSessionEventsResponse_EventType {
	if x != nil {
		return x.Type
	}
	return WatchSessionEventsResponse_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchSessionEventsResponse) GetSession() *BfdSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *WatchSessionEventsResponse) GetPreviousState() SessionState {
	if x != nil {
		return x.PreviousState
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *WatchSessionEventsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// EchoSession represents a single RFC 9747 unaffiliated echo session.
type EchoSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PeerAddress is the remote system's IP address (echo target).
	PeerAddress string `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	// LocalAddress is the local system's IP address.
	LocalAddress string `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	// InterfaceName is the optional outbound interface (SO_BINDTODEVICE).
	InterfaceName string `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// TxInterval is the echo transmit interval. RFC 9747 Section 3.3:
	// locally provisioned, not negotiated with the peer.
	TxInterval *durationpb.Duration `protobuf:"bytes,4,opt,name=tx_interval,json=txInterval,proto3" json:"tx_interval,omitempty"`
	// DetectMultiplier sets DetectionTime = DetectMult * TxInterval.
	DetectMultiplier uint32 `protobuf:"varint,5,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	// LocalDiscriminator is the discriminator allocated for this session.
	LocalDiscriminator uint32 `protobuf:"varint,6,opt,name=local_discriminator,json=localDiscriminator,proto3" json:"local_discriminator,omitempty"`
	// LocalState is the current FSM state.
	LocalState SessionState `protobuf:"varint,7,opt,name=local_state,json=localState,proto3,enum=bfd.v1.SessionState" json:"local_state,omitempty"`
	// LocalDiagnostic is the latest diagnostic code (RFC 5880 Section 4.1).
	LocalDiagnostic DiagnosticCode `protobuf:"varint,8,opt,name=local_diagnostic,json=localDiagnostic,proto3,enum=bfd.v1.DiagnosticCode" json:"local_diagnostic,omitempty"`
	// PacketsSent is the total echo packets transmitted.
	PacketsSent uint64 `protobuf:"varint,9,opt,name=packets_sent,json=packetsSent,proto3" json:"packets_sent,omitempty"`
	// PacketsReceived is the total echo packets received back.
	PacketsReceived uint64 `protobuf:"varint,10,opt,name=packets_received,json=packetsReceived,proto3" json:"packets_received,omitempty"`
	// LastStateChange is the timestamp of the most recent FSM transition.
	LastStateChange *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_state_change,json=lastStateChange,proto3" json:"last_state_change,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EchoSession) Reset() {
	*x = EchoSession{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoSession) ProtoMessage() {}

func (x *EchoSession) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoSession.ProtoReflect.Descriptor instead.
func (*EchoSession) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{12}
}

func (x *EchoSession) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *EchoSession) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *EchoSession) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *EchoSession) GetTxInterval() *durationpb.Duration {
	if x != nil {
		return x.TxInterval
	}
	return nil
}

func (x *EchoSession) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *EchoSession) GetLocalDiscriminator() uint32 {
	if x != nil {
		return x.LocalDiscriminator
	}
	return 0
}

func (x *EchoSession) GetLocalState() SessionState {
	if x != nil {
		return x.LocalState
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *EchoSession) GetLocalDiagnostic() DiagnosticCode {
	if x != nil {
		return x.LocalDiagnostic
	}
	return DiagnosticCode_DIAGNOSTIC_CODE_UNSPECIFIED
}

func (x *EchoSession) GetPacketsSent() uint64 {
	if x != nil {
		return x.PacketsSent
	}
	return 0
}

func (x *EchoSession) GetPacketsReceived() uint64 {
	if x != nil {
		return x.PacketsReceived
	}
	return 0
}

func (x *EchoSession) GetLastStateChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastStateChange
	}
	return nil
}

// AddEchoSessionRequest creates a new RFC 9747 echo session.
type AddEchoSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PeerAddress      string                 `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	LocalAddress     string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	InterfaceName    string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	TxInterval       *durationpb.Duration   `protobuf:"bytes,4,opt,name=tx_interval,json=txInterval,proto3" json:"tx_interval,omitempty"`
	DetectMultiplier uint32                 `protobuf:"varint,5,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddEchoSessionRequest) Reset() {
	*x = AddEchoSessionRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEchoSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEchoSessionRequest) ProtoMessage() {}

func (x *AddEchoSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEchoSessionRequest.ProtoReflect.Descriptor instead.
func (*AddEchoSessionRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{13}
}

func (x *AddEchoSessionRequest) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *AddEchoSessionRequest) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *AddEchoSessionRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *AddEchoSessionRequest) GetTxInterval() *durationpb.Duration {
	if x != nil {
		return x.TxInterval
	}
	return nil
}

func (x *AddEchoSessionRequest) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

// AddEchoSessionResponse returns the newly created echo session.
type AddEchoSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *EchoSession           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEchoSessionResponse) Reset() {
	*x = AddEchoSessionResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEchoSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEchoSessionResponse) ProtoMessage() {}

func (x *AddEchoSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEchoSessionResponse.ProtoReflect.Descriptor instead.
func (*AddEchoSessionResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{14}
}

func (x *AddEchoSessionResponse) GetSession() *EchoSession {
	if x != nil {
		return x.Session
	}
	return nil
}

// DeleteEchoSessionRequest removes an echo session by its local discriminator.
type DeleteEchoSessionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LocalDiscriminator uint32                 `protobuf:"varint,1,opt,name=local_discriminator,json=localDiscriminator,proto3" json:"local_discriminator,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteEchoSessionRequest) Reset() {
	*x = DeleteEchoSessionRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEchoSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEchoSessionRequest) ProtoMessage() {}

func (x *DeleteEchoSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEchoSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteEchoSessionRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteEchoSessionRequest) GetLocalDiscriminator() uint32 {
	if x != nil {
		return x.LocalDiscriminator
	}
	return 0
}

// DeleteEchoSessionResponse is empty on success.
type DeleteEchoSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEchoSessionResponse) Reset() {
	*x = DeleteEchoSessionResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEchoSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEchoSessionResponse) ProtoMessage() {}

func (x *DeleteEchoSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEchoSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteEchoSessionResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{16}
}

// ListEchoSessionsRequest retrieves all active echo sessions.
type ListEchoSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEchoSessionsRequest) Reset() {
	*x = ListEchoSessionsRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEchoSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEchoSessionsRequest) ProtoMessage() {}

func (x *ListEchoSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEchoSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListEchoSessionsRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{17}
}

// ListEchoSessionsResponse contains all active echo sessions.
type ListEchoSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*EchoSession         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEchoSessionsResponse) Reset() {
	*x = ListEchoSessionsResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEchoSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEchoSessionsResponse) ProtoMessage() {}

func (x *ListEchoSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEchoSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListEchoSessionsResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{18}
}

func (x *ListEchoSessionsResponse) GetSessions() []*EchoSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// MicroBFDGroup represents an RFC 7130 micro-BFD group bound to a LAG.
type MicroBFDGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// LagInterface is the logical LAG interface name (e.g., "bond0").
	LagInterface string `protobuf:"bytes,1,opt,name=lag_interface,json=lagInterface,proto3" json:"lag_interface,omitempty"`
	// MemberLinks lists the physical member link names participating in
	// the LAG. RFC 7130 Section 2: one micro-BFD session per member link.
	MemberLinks []string `protobuf:"bytes,2,rep,name=member_links,json=memberLinks,proto3" json:"member_links,omitempty"`
	// PeerAddress is the remote system's IP address for every member session.
	PeerAddress string `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	// LocalAddress is the local system's IP address.
	LocalAddress string `protobuf:"bytes,4,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	// DesiredMinTxInterval is the BFD timer for member sessions. RFC 7130
	// Section 2.2: timer values MAY differ per member but are expected to
	// be the same within a group.
	DesiredMinTxInterval *durationpb.Duration `protobuf:"bytes,5,opt,name=desired_min_tx_interval,json=desiredMinTxInterval,proto3" json:"desired_min_tx_interval,omitempty"`
	// RequiredMinRxInterval is the minimum acceptable RX interval.
	RequiredMinRxInterval *durationpb.Duration `protobuf:"bytes,6,opt,name=required_min_rx_interval,json=requiredMinRxInterval,proto3" json:"required_min_rx_interval,omitempty"`
	// DetectMultiplier is the detection time multiplier.
	DetectMultiplier uint32 `protobuf:"varint,7,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	// MinActiveLinks is the minimum number of member links that must be Up
	// for the LAG to be considered operational. Must satisfy
	// 1 <= MinActiveLinks <= len(MemberLinks).
	MinActiveLinks uint32 `protobuf:"varint,8,opt,name=min_active_links,json=minActiveLinks,proto3" json:"min_active_links,omitempty"`
	// AggregateUp reflects whether the group's aggregate state is Up.
	AggregateUp bool `protobuf:"varint,9,opt,name=aggregate_up,json=aggregateUp,proto3" json:"aggregate_up,omitempty"`
	// UpMemberCount is the current count of member sessions in state Up.
	UpMemberCount uint32 `protobuf:"varint,10,opt,name=up_member_count,json=upMemberCount,proto3" json:"up_member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroBFDGroup) Reset() {
	*x = MicroBFDGroup{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroBFDGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroBFDGroup) ProtoMessage() {}

func (x *MicroBFDGroup) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroBFDGroup.ProtoReflect.Descriptor instead.
func (*MicroBFDGroup) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{19}
}

func (x *MicroBFDGroup) GetLagInterface() string {
	if x != nil {
		return x.LagInterface
	}
	return ""
}

func (x *MicroBFDGroup) GetMemberLinks() []string {
	if x != nil {
		return x.MemberLinks
	}
	return nil
}

func (x *MicroBFDGroup) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *MicroBFDGroup) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *MicroBFDGroup) GetDesiredMinTxInterval() *durationpb.Duration {
	if x != nil {
		return x.DesiredMinTxInterval
	}
	return nil
}

func (x *MicroBFDGroup) GetRequiredMinRxInterval() *durationpb.Duration {
	if x != nil {
		return x.RequiredMinRxInterval
	}
	return nil
}

func (x *MicroBFDGroup) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *MicroBFDGroup) GetMinActiveLinks() uint32 {
	if x != nil {
		return x.MinActiveLinks
	}
	return 0
}

func (x *MicroBFDGroup) GetAggregateUp() bool {
	if x != nil {
		return x.AggregateUp
	}
	return false
}

func (x *MicroBFDGroup) GetUpMemberCount() uint32 {
	if x != nil {
		return x.UpMemberCount
	}
	return 0
}

// AddMicroBFDGroupRequest creates a new RFC 7130 micro-BFD group.
type AddMicroBFDGroupRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LagInterface          string                 `protobuf:"bytes,1,opt,name=lag_interface,json=lagInterface,proto3" json:"lag_interface,omitempty"`
	MemberLinks           []string               `protobuf:"bytes,2,rep,name=member_links,json=memberLinks,proto3" json:"member_links,omitempty"`
	PeerAddress           string                 `protobuf:"bytes,3,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	LocalAddress          string                 `protobuf:"bytes,4,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	DesiredMinTxInterval  *durationpb.Duration   `protobuf:"bytes,5,opt,name=desired_min_tx_interval,json=desiredMinTxInterval,proto3" json:"desired_min_tx_interval,omitempty"`
	RequiredMinRxInterval *durationpb.Duration   `protobuf:"bytes,6,opt,name=required_min_rx_interval,json=requiredMinRxInterval,proto3" json:"required_min_rx_interval,omitempty"`
	DetectMultiplier      uint32                 `protobuf:"varint,7,opt,name=detect_multiplier,json=detectMultiplier,proto3" json:"detect_multiplier,omitempty"`
	MinActiveLinks        uint32                 `protobuf:"varint,8,opt,name=min_active_links,json=minActiveLinks,proto3" json:"min_active_links,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AddMicroBFDGroupRequest) Reset() {
	*x = AddMicroBFDGroupRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMicroBFDGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMicroBFDGroupRequest) ProtoMessage() {}

func (x *AddMicroBFDGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMicroBFDGroupRequest.ProtoReflect.Descriptor instead.
func (*AddMicroBFDGroupRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{20}
}

func (x *AddMicroBFDGroupRequest) GetLagInterface() string {
	if x != nil {
		return x.LagInterface
	}
	return ""
}

func (x *AddMicroBFDGroupRequest) GetMemberLinks() []string {
	if x != nil {
		return x.MemberLinks
	}
	return nil
}

func (x *AddMicroBFDGroupRequest) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *AddMicroBFDGroupRequest) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *AddMicroBFDGroupRequest) GetDesiredMinTxInterval() *durationpb.Duration {
	if x != nil {
		return x.DesiredMinTxInterval
	}
	return nil
}

func (x *AddMicroBFDGroupRequest) GetRequiredMinRxInterval() *durationpb.Duration {
	if x != nil {
		return x.RequiredMinRxInterval
	}
	return nil
}

func (x *AddMicroBFDGroupRequest) GetDetectMultiplier() uint32 {
	if x != nil {
		return x.DetectMultiplier
	}
	return 0
}

func (x *AddMicroBFDGroupRequest) GetMinActiveLinks() uint32 {
	if x != nil {
		return x.MinActiveLinks
	}
	return 0
}

// AddMicroBFDGroupResponse returns the newly created group.
type AddMicroBFDGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *MicroBFDGroup         `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMicroBFDGroupResponse) Reset() {
	*x = AddMicroBFDGroupResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMicroBFDGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMicroBFDGroupResponse) ProtoMessage() {}

func (x *AddMicroBFDGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMicroBFDGroupResponse.ProtoReflect.Descriptor instead.
func (*AddMicroBFDGroupResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{21}
}

func (x *AddMicroBFDGroupResponse) GetGroup() *MicroBFDGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

// DeleteMicroBFDGroupRequest removes a micro-BFD group by LAG interface.
type DeleteMicroBFDGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LagInterface  string                 `protobuf:"bytes,1,opt,name=lag_interface,json=lagInterface,proto3" json:"lag_interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMicroBFDGroupRequest) Reset() {
	*x = DeleteMicroBFDGroupRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMicroBFDGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMicroBFDGroupRequest) ProtoMessage() {}

func (x *DeleteMicroBFDGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMicroBFDGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteMicroBFDGroupRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteMicroBFDGroupRequest) GetLagInterface() string {
	if x != nil {
		return x.LagInterface
	}
	return ""
}

// DeleteMicroBFDGroupResponse is empty on success.
type DeleteMicroBFDGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMicroBFDGroupResponse) Reset() {
	*x = DeleteMicroBFDGroupResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMicroBFDGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMicroBFDGroupResponse) ProtoMessage() {}

func (x *DeleteMicroBFDGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMicroBFDGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteMicroBFDGroupResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{23}
}

// ListMicroBFDGroupsRequest retrieves all active micro-BFD groups.
type ListMicroBFDGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMicroBFDGroupsRequest) Reset() {
	*x = ListMicroBFDGroupsRequest{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMicroBFDGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMicroBFDGroupsRequest) ProtoMessage() {}

func (x *ListMicroBFDGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMicroBFDGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListMicroBFDGroupsRequest) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{24}
}

// ListMicroBFDGroupsResponse contains all active micro-BFD groups.
type ListMicroBFDGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*MicroBFDGroup       `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMicroBFDGroupsResponse) Reset() {
	*x = ListMicroBFDGroupsResponse{}
	mi := &file_bfd_v1_bfd_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMicroBFDGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMicroBFDGroupsResponse) ProtoMessage() {}

func (x *ListMicroBFDGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bfd_v1_bfd_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMicroBFDGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListMicroBFDGroupsResponse) Descriptor() ([]byte, []int) {
	return file_bfd_v1_bfd_proto_rawDescGZIP(), []int{25}
}

func (x *ListMicroBFDGroupsResponse) GetGroups() []*MicroBFDGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_bfd_v1_bfd_proto protoreflect.FileDescriptor

const file_bfd_v1_bfd_proto_rawDesc = "" +
	"\n" +
	"\x10bfd/v1/bfd.proto\x12\x06bfd.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\t\n" +
	"\n" +
	"BfdSession\x12*\n" +
	"\fpeer_address\x18\x01 \x01(\tB\a\xbaH\x04r\x02p\x01R\vpeerAddress\x12,\n" +
	"\rlocal_address\x18\x02 \x01(\tB\a\xbaH\x04r\x02p\x01R\flocalAddress\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.bfd.v1.SessionTypeR\x04type\x125\n" +
	"\vlocal_state\x18\x05 \x01(\x0e2\x14.bfd.v1.SessionStateR\n" +
	"localState\x127\n" +
	"\fremote_state\x18\x06 \x01(\x0e2\x14.bfd.v1.SessionStateR\vremoteState\x12A\n" +
	"\x10local_diagnostic\x18\a \x01(\x0e2\x16.bfd.v1.DiagnosticCodeR\x0flocalDiagnostic\x12/\n" +
	"\x13local_discriminator\x18\b \x01(\rR\x12localDiscriminator\x121\n" +
	"\x14remote_discriminator\x18\t \x01(\rR\x13remoteDiscriminator\x12P\n" +
	"\x17desired_min_tx_interval\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x14desiredMinTxInterval\x12R\n" +
	"\x18required_min_rx_interval\x18\v \x01(\v2\x19.google.protobuf.DurationR\x15requiredMinRxInterval\x12N\n" +
	"\x16remote_min_rx_interval\x18\f \x01(\v2\x19.google.protobuf.DurationR\x13remoteMinRxInterval\x124\n" +
	"\x11detect_multiplier\x18\r \x01(\rB\a\xbaH\x04*\x02(\x01R\x10detectMultiplier\x12O\n" +
	"\x16negotiated_tx_interval\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\x14negotiatedTxInterval\x12@\n" +
	"\x0edetection_time\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\rdetectionTime\x127\n" +
	"\tauth_type\x18\x10 \x01(\x0e2\x1a.bfd.v1.AuthenticationTypeR\bauthType\x12F\n" +
	"\x11last_state_change\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastStateChange\x12L\n" +
	"\x14last_packet_received\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastPacketReceived\x123\n" +
	"\bcounters\x18\x13 \x01(\v2\x17.bfd.v1.SessionCountersR\bcounters\"\xda\x01\n" +
	"\x0fSessionCounters\x12!\n" +
	"\fpackets_sent\x18\x01 \x01(\x04R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\x02 \x01(\x04R\x0fpacketsReceived\x12'\n" +
	"\x0fpackets_dropped\x18\x03 \x01(\x04R\x0epacketsDropped\x12+\n" +
	"\x11state_transitions\x18\x04 \x01(\x04R\x10stateTransitions\x12#\n" +
	"\rauth_failures\x18\x05 \x01(\x04R\fauthFailures\"\x9d\x04\n" +
	"\x11AddSessionRequest\x12*\n" +
	"\fpeer_address\x18\x01 \x01(\tB\a\xbaH\x04r\x02p\x01R\vpeerAddress\x12,\n" +
	"\rlocal_address\x18\x02 \x01(\tB\a\xbaH\x04r\x02p\x01R\flocalAddress\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.bfd.v1.SessionTypeR\x04type\x12P\n" +
	"\x17desired_min_tx_interval\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x14desiredMinTxInterval\x12R\n" +
	"\x18required_min_rx_interval\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x15requiredMinRxInterval\x124\n" +
	"\x11detect_multiplier\x18\a \x01(\rB\a\xbaH\x04*\x02(\x01R\x10detectMultiplier\x127\n" +
	"\tauth_type\x18\b \x01(\x0e2\x1a.bfd.v1.AuthenticationTypeR\bauthType\x12(\n" +
	"\vauth_key_id\x18\t \x01(\rB\b\xbaH\x05*\x03\x18\xff\x01R\tauthKeyId\x12\x1f\n" +
	"\vauth_secret\x18\n" +
	" \x01(\fR\n" +
	"authSecret\"B\n" +
	"\x12AddSessionResponse\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.bfd.v1.BfdSessionR\asession\"G\n" +
	"\x14DeleteSessionRequest\x12/\n" +
	"\x13local_discriminator\x18\x01 \x01(\rR\x12localDiscriminator\"\x17\n" +
	"\x15DeleteSessionResponse\"\x15\n" +
	"\x13ListSessionsRequest\"F\n" +
	"\x14ListSessionsResponse\x12.\n" +
	"\bsessions\x18\x01 \x03(\v2\x12.bfd.v1.BfdSessionR\bsessions\"y\n" +
	"\x11GetSessionRequest\x121\n" +
	"\x13local_discriminator\x18\x01 \x01(\rH\x00R\x12localDiscriminator\x12#\n" +
	"\fpeer_address\x18\x02 \x01(\tH\x00R\vpeerAddressB\f\n" +
	"\n" +
	"identifier\"B\n" +
	"\x12GetSessionResponse\x12,\n" +
	"\asession\x18\x01 \x01(\v2\x12.bfd.v1.BfdSessionR\asession\"D\n" +
	"\x19WatchSessionEventsRequest\x12'\n" +
	"\x0finclude_current\x18\x01 \x01(\bR\x0eincludeCurrent\"\x88\x03\n" +
	"\x1aWatchSessionEventsResponse\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.bfd.v1.WatchSessionEventsResponse.EventTypeR\x04type\x12,\n" +
	"\asession\x18\x02 \x01(\v2\x12.bfd.v1.BfdSessionR\asession\x12;\n" +
	"\x0eprevious_state\x18\x03 \x01(\x0e2\x14.bfd.v1.SessionStateR\rpreviousState\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_STATE_CHANGE\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_SESSION_ADDED\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_SESSION_DELETED\x10\x03\"\xc4\x04\n" +
	"\vEchoSession\x12*\n" +
	"\fpeer_address\x18\x01 \x01(\tB\a\xbaH\x04r\x02p\x01R\vpeerAddress\x12,\n" +
	"\rlocal_address\x18\x02 \x01(\tB\a\xbaH\x04r\x02p\x01R\flocalAddress\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12:\n" +
	"\vtx_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"txInterval\x127\n" +
	"\x11detect_multiplier\x18\x05 \x01(\rB\n" +
	"\xbaH\a*\x05\x18\xff\x01(\x01R\x10detectMultiplier\x12/\n" +
	"\x13local_discriminator\x18\x06 \x01(\rR\x12localDiscriminator\x125\n" +
	"\vlocal_state\x18\a \x01(\x0e2\x14.bfd.v1.SessionStateR\n" +
	"localState\x12A\n" +
	"\x10local_diagnostic\x18\b \x01(\x0e2\x16.bfd.v1.DiagnosticCodeR\x0flocalDiagnostic\x12!\n" +
	"\fpackets_sent\x18\t \x01(\x04R\vpacketsSent\x12)\n" +
	"\x10packets_received\x18\n" +
	" \x01(\x04R\x0fpacketsReceived\x12F\n" +
	"\x11last_state_change\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0flastStateChange\"\x8d\x02\n" +
	"\x15AddEchoSessionRequest\x12*\n" +
	"\fpeer_address\x18\x01 \x01(\tB\a\xbaH\x04r\x02p\x01R\vpeerAddress\x12,\n" +
	"\rlocal_address\x18\x02 \x01(\tB\a\xbaH\x04r\x02p\x01R\flocalAddress\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12:\n" +
	"\vtx_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"txInterval\x127\n" +
	"\x11detect_multiplier\x18\x05 \x01(\rB\n" +
	"\xbaH\a*\x05\x18\xff\x01(\x01R\x10detectMultiplier\"G\n" +
	"\x16AddEchoSessionResponse\x12-\n" +
	"\asession\x18\x01 \x01(\v2\x13.bfd.v1.EchoSessionR\asession\"K\n" +
	"\x18DeleteEchoSessionRequest\x12/\n" +
	"\x13local_discriminator\x18\x01 \x01(\rR\x12localDiscriminator\"\x1b\n" +
	"\x19DeleteEchoSessionResponse\"\x19\n" +
	"\x17ListEchoSessionsRequest\"K\n" +
	"\x18ListEchoSessionsResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.bfd.v1.EchoSessionR\bsessions\"\x8e\x04\n" +
	"\rMicroBFDGroup\x12#\n" +
	"\rlag_interface\x18\x01 \x01(\tR\flagInterface\x12!\n" +
	"\fmember_links\x18\x02 \x03(\tR\vmemberLinks\x12*\n" +
	"\fpeer_address\x18\x03 \x01(\tB\a\xbaH\x04r\x02p\x01R\vpeerAddress\x12,\n" +
	"\rlocal_address\x18\x04 \x01(\tB\a\xbaH\x04r\x02p\x01R\flocalAddress\x12P\n" +
	"\x17desired_min_tx_interval\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x14desiredMinTxInterval\x12R\n" +
	"\x18required_min_rx_interval\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x15requiredMinRxInterval\x127\n" +
	"\x11detect_multiplier\x18\a \x01(\rB\n" +
	"\xbaH\a*\x05\x18\xff\x01(\x01R\x10detectMultiplier\x121\n" +
	"\x10min_active_links\x18\b \x01(\rB\a\xbaH\x04*\x02(\x01R\x0eminActiveLinks\x12!\n" +
	"\faggregate_up\x18\t \x01(\bR\vaggregateUp\x12&\n" +
	"\x0fup_member_count\x18\n" +
	" \x01(\rR\rupMemberCount\"\xcd\x03\n" +
	"\x17AddMicroBFDGroupRequest\x12#\n" +
	"\rlag_interface\x18\x01 \x01(\tR\flagInterface\x12!\n" +
	"\fmember_links\x18\x02 \x03(\tR\vmemberLinks\x12*\n" +
	"\fpeer_address\x18\x03 \x01(\tB\a\xbaH\x04r\x02p\x01R\vpeerAddress\x12,\n" +
	"\rlocal_address\x18\x04 \x01(\tB\a\xbaH\x04r\x02p\x01R\flocalAddress\x12P\n" +
	"\x17desired_min_tx_interval\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x14desiredMinTxInterval\x12R\n" +
	"\x18required_min_rx_interval\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x15requiredMinRxInterval\x127\n" +
	"\x11detect_multiplier\x18\a \x01(\rB\n" +
	"\xbaH\a*\x05\x18\xff\x01(\x01R\x10detectMultiplier\x121\n" +
	"\x10min_active_links\x18\b \x01(\rB\a\xbaH\x04*\x02(\x01R\x0eminActiveLinks\"G\n" +
	"\x18AddMicroBFDGroupResponse\x12+\n" +
	"\x05group\x18\x01 \x01(\v2\x15.bfd.v1.MicroBFDGroupR\x05group\"A\n" +
	"\x1aDeleteMicroBFDGroupRequest\x12#\n" +
	"\rlag_interface\x18\x01 \x01(\tR\flagInterface\"\x1d\n" +
	"\x1bDeleteMicroBFDGroupResponse\"\x1b\n" +
	"\x19ListMicroBFDGroupsRequest\"K\n" +
	"\x1aListMicroBFDGroupsResponse\x12-\n" +
	"\x06groups\x18\x01 \x03(\v2\x15.bfd.v1.MicroBFDGroupR\x06groups*\x91\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SESSION_STATE_ADMIN_DOWN\x10\x01\x12\x16\n" +
	"\x12SESSION_STATE_DOWN\x10\x02\x12\x16\n" +
	"\x12SESSION_STATE_INIT\x10\x03\x12\x14\n" +
	"\x10SESSION_STATE_UP\x10\x04*\xf2\x02\n" +
	"\x0eDiagnosticCode\x12\x1f\n" +
	"\x1bDIAGNOSTIC_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DIAGNOSTIC_CODE_NONE\x10\x01\x12(\n" +
	"$DIAGNOSTIC_CODE_CONTROL_TIME_EXPIRED\x10\x02\x12\x1f\n" +
	"\x1bDIAGNOSTIC_CODE_ECHO_FAILED\x10\x03\x12!\n" +
	"\x1dDIAGNOSTIC_CODE_NEIGHBOR_DOWN\x10\x04\x12$\n" +
	" DIAGNOSTIC_CODE_FORWARDING_RESET\x10\x05\x12\x1d\n" +
	"\x19DIAGNOSTIC_CODE_PATH_DOWN\x10\x06\x12$\n" +
	" DIAGNOSTIC_CODE_CONCAT_PATH_DOWN\x10\a\x12\x1e\n" +
	"\x1aDIAGNOSTIC_CODE_ADMIN_DOWN\x10\b\x12,\n" +
	"(DIAGNOSTIC_CODE_REVERSE_CONCAT_PATH_DOWN\x10\t*\xa4\x02\n" +
	"\x12AuthenticationType\x12#\n" +
	"\x1fAUTHENTICATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AUTHENTICATION_TYPE_NONE\x10\x01\x12'\n" +
	"#AUTHENTICATION_TYPE_SIMPLE_PASSWORD\x10\x02\x12!\n" +
	"\x1dAUTHENTICATION_TYPE_KEYED_MD5\x10\x03\x12,\n" +
	"(AUTHENTICATION_TYPE_METICULOUS_KEYED_MD5\x10\x04\x12\"\n" +
	"\x1eAUTHENTICATION_TYPE_KEYED_SHA1\x10\x05\x12-\n" +
	")AUTHENTICATION_TYPE_METICULOUS_KEYED_SHA1\x10\x06*\xc8\x01\n" +
	"\vSessionType\x12\x1c\n" +
	"\x18SESSION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SESSION_TYPE_SINGLE_HOP\x10\x01\x12\x1a\n" +
	"\x16SESSION_TYPE_MULTI_HOP\x10\x02\x12\x15\n" +
	"\x11SESSION_TYPE_ECHO\x10\x03\x12\x1a\n" +
	"\x16SESSION_TYPE_MICRO_BFD\x10\x04\x12\x16\n" +
	"\x12SESSION_TYPE_VXLAN\x10\x05\x12\x17\n" +
	"\x13SESSION_TYPE_GENEVE\x10\x062\x8e\x03\n" +
	"\n" +
	"BfdService\x12C\n" +
	"\n" +
	"AddSession\x12\x19.bfd.v1.AddSessionRequest\x1a\x1a.bfd.v1.AddSessionResponse\x12L\n" +
	"\rDeleteSession\x12\x1c.bfd.v1.DeleteSessionRequest\x1a\x1d.bfd.v1.DeleteSessionResponse\x12I\n" +
	"\fListSessions\x12\x1b.bfd.v1.ListSessionsRequest\x1a\x1c.bfd.v1.ListSessionsResponse\x12C\n" +
	"\n" +
	"GetSession\x12\x19.bfd.v1.GetSessionRequest\x1a\x1a.bfd.v1.GetSessionResponse\x12]\n" +
	"\x12WatchSessionEvents\x12!.bfd.v1.WatchSessionEventsRequest\x1a\".bfd.v1.WatchSessionEventsResponse0\x012\x8f\x02\n" +
	"\vEchoService\x12O\n" +
	"\x0eAddEchoSession\x12\x1d.bfd.v1.AddEchoSessionRequest\x1a\x1e.bfd.v1.AddEchoSessionResponse\x12X\n" +
	"\x11DeleteEchoSession\x12 .bfd.v1.DeleteEchoSessionRequest\x1a!.bfd.v1.DeleteEchoSessionResponse\x12U\n" +
	"\x10ListEchoSessions\x12\x1f.bfd.v1.ListEchoSessionsRequest\x1a .bfd.v1.ListEchoSessionsResponse2\xa5\x02\n" +
	"\x0fMicroBFDService\x12U\n" +
	"\x10AddMicroBFDGroup\x12\x1f.bfd.v1.AddMicroBFDGroupRequest\x1a .bfd.v1.AddMicroBFDGroupResponse\x12^\n" +
	"\x13DeleteMicroBFDGroup\x12\".bfd.v1.DeleteMicroBFDGroupRequest\x1a#.bfd.v1.DeleteMicroBFDGroupResponse\x12[\n" +
	"\x12ListMicroBFDGroups\x12!.bfd.v1.ListMicroBFDGroupsRequest\x1a\".bfd.v1.ListMicroBFDGroupsResponseB\x82\x01\n" +
	"\n" +
	"com.bfd.v1B\bBfdProtoP\x01Z1github.com/dantte-lp/gobfd/pkg/bfdpb/bfd/v1;bfdv1\xa2\x02\x03BXX\xaa\x02\x06Bfd.V1\xca\x02\x06Bfd\\V1\xe2\x02\x12Bfd\\V1\\GPBMetadata\xea\x02\aBfd::V1b\x06proto3"

var (
	file_bfd_v1_bfd_proto_rawDescOnce sync.Once
	file_bfd_v1_bfd_proto_rawDescData []byte
)

func file_bfd_v1_bfd_proto_rawDescGZIP() []byte {
	file_bfd_v1_bfd_proto_rawDescOnce.Do(func() {
		file_bfd_v1_bfd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bfd_v1_bfd_proto_rawDesc), len(file_bfd_v1_bfd_proto_rawDesc)))
	})
	return file_bfd_v1_bfd_proto_rawDescData
}

var file_bfd_v1_bfd_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_bfd_v1_bfd_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_bfd_v1_bfd_proto_goTypes = []any{
	(SessionState)(0),                         // 0: bfd.v1.SessionState
	(DiagnosticCode)(0),                       // 1: bfd.v1.DiagnosticCode
	(AuthenticationType)(0),                   // 2: bfd.v1.AuthenticationType
	(SessionType)(0),                          // 3: bfd.v1.SessionType
	(WatchSessionEventsResponse_EventType)(0), // 4: bfd.v1.WatchSessionEventsResponse.EventType
	(*BfdSession)(nil),                        // 5: bfd.v1.BfdSession
	(*SessionCounters)(nil),                   // 6: bfd.v1.SessionCounters
	(*AddSessionRequest)(nil),                 // 7: bfd.v1.AddSessionRequest
	(*AddSessionResponse)(nil),                // 8: bfd.v1.AddSessionResponse
	(*DeleteSessionRequest)(nil),              // 9: bfd.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),             // 10: bfd.v1.DeleteSessionResponse
	(*ListSessionsRequest)(nil),               // 11: bfd.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),              // 12: bfd.v1.ListSessionsResponse
	(*GetSessionRequest)(nil),                 // 13: bfd.v1.GetSessionRequest
	(*GetSessionResponse)(nil),                // 14: bfd.v1.GetSessionResponse
	(*WatchSessionEventsRequest)(nil),         // 15: bfd.v1.WatchSessionEventsRequest
	(*WatchSessionEventsResponse)(nil),        // 16: bfd.v1.WatchSessionEventsResponse
	(*EchoSession)(nil),                       // 17: bfd.v1.EchoSession
	(*AddEchoSessionRequest)(nil),             // 18: bfd.v1.AddEchoSessionRequest
	(*AddEchoSessionResponse)(nil),            // 19: bfd.v1.AddEchoSessionResponse
	(*DeleteEchoSessionRequest)(nil),          // 20: bfd.v1.DeleteEchoSessionRequest
	(*DeleteEchoSessionResponse)(nil),         // 21: bfd.v1.DeleteEchoSessionResponse
	(*ListEchoSessionsRequest)(nil),           // 22: bfd.v1.ListEchoSessionsRequest
	(*ListEchoSessionsResponse)(nil),          // 23: bfd.v1.ListEchoSessionsResponse
	(*MicroBFDGroup)(nil),                     // 24: bfd.v1.MicroBFDGroup
	(*AddMicroBFDGroupRequest)(nil),           // 25: bfd.v1.AddMicroBFDGroupRequest
	(*AddMicroBFDGroupResponse)(nil),          // 26: bfd.v1.AddMicroBFDGroupResponse
	(*DeleteMicroBFDGroupRequest)(nil),        // 27: bfd.v1.DeleteMicroBFDGroupRequest
	(*DeleteMicroBFDGroupResponse)(nil),       // 28: bfd.v1.DeleteMicroBFDGroupResponse
	(*ListMicroBFDGroupsRequest)(nil),         // 29: bfd.v1.ListMicroBFDGroupsRequest
	(*ListMicroBFDGroupsResponse)(nil),        // 30: bfd.v1.ListMicroBFDGroupsResponse
	(*durationpb.Duration)(nil),               // 31: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),             // 32: google.protobuf.Timestamp
}
var file_bfd_v1_bfd_proto_depIdxs = []int32{
	3,  // 0: bfd.v1.BfdSession.type:type_name -> bfd.v1.SessionType
	0,  // 1: bfd.v1.BfdSession.local_state:type_name -> bfd.v1.SessionState
	0,  // 2: bfd.v1.BfdSession.remote_state:type_name -> bfd.v1.SessionState
	1,  // 3: bfd.v1.BfdSession.local_diagnostic:type_name -> bfd.v1.DiagnosticCode
	31, // 4: bfd.v1.BfdSession.desired_min_tx_interval:type_name -> google.protobuf.Duration
	31, // 5: bfd.v1.BfdSession.required_min_rx_interval:type_name -> google.protobuf.Duration
	31, // 6: bfd.v1.BfdSession.remote_min_rx_interval:type_name -> google.protobuf.Duration
	31, // 7: bfd.v1.BfdSession.negotiated_tx_interval:type_name -> google.protobuf.Duration
	31, // 8: bfd.v1.BfdSession.detection_time:type_name -> google.protobuf.Duration
	2,  // 9: bfd.v1.BfdSession.auth_type:type_name -> bfd.v1.AuthenticationType
	32, // 10: bfd.v1.BfdSession.last_state_change:type_name -> google.protobuf.Timestamp
	32, // 11: bfd.v1.BfdSession.last_packet_received:type_name -> google.protobuf.Timestamp
	6,  // 12: bfd.v1.BfdSession.counters:type_name -> bfd.v1.SessionCounters
	3,  // 13: bfd.v1.AddSessionRequest.type:type_name -> bfd.v1.SessionType
	31, // 14: bfd.v1.AddSessionRequest.desired_min_tx_interval:type_name -> google.protobuf.Duration
	31, // 15: bfd.v1.AddSessionRequest.required_min_rx_interval:type_name -> google.protobuf.Duration
	2,  // 16: bfd.v1.AddSessionRequest.auth_type:type_name -> bfd.v1.AuthenticationType
	5,  // 17: bfd.v1.AddSessionResponse.session:type_name -> bfd.v1.BfdSession
	5,  // 18: bfd.v1.ListSessionsResponse.sessions:type_name -> bfd.v1.BfdSession
	5,  // 19: bfd.v1.GetSessionResponse.session:type_name -> bfd.v1.BfdSession
	4,  // 20: bfd.v1.WatchSessionEventsResponse.type:type_name -> bfd.v1.WatchSessionEventsResponse.EventType
	5,  // 21: bfd.v1.WatchSessionEventsResponse.session:type_name -> bfd.v1.BfdSession
	0,  // 22: bfd.v1.WatchSessionEventsResponse.previous_state:type_name -> bfd.v1.SessionState
	32, // 23: bfd.v1.WatchSessionEventsResponse.timestamp:type_name -> google.protobuf.Timestamp
	31, // 24: bfd.v1.EchoSession.tx_interval:type_name -> google.protobuf.Duration
	0,  // 25: bfd.v1.EchoSession.local_state:type_name -> bfd.v1.SessionState
	1,  // 26: bfd.v1.EchoSession.local_diagnostic:type_name -> bfd.v1.DiagnosticCode
	32, // 27: bfd.v1.EchoSession.last_state_change:type_name -> google.protobuf.Timestamp
	31, // 28: bfd.v1.AddEchoSessionRequest.tx_interval:type_name -> google.protobuf.Duration
	17, // 29: bfd.v1.AddEchoSessionResponse.session:type_name -> bfd.v1.EchoSession
	17, // 30: bfd.v1.ListEchoSessionsResponse.sessions:type_name -> bfd.v1.EchoSession
	31, // 31: bfd.v1.MicroBFDGroup.desired_min_tx_interval:type_name -> google.protobuf.Duration
	31, // 32: bfd.v1.MicroBFDGroup.required_min_rx_interval:type_name -> google.protobuf.Duration
	31, // 33: bfd.v1.AddMicroBFDGroupRequest.desired_min_tx_interval:type_name -> google.protobuf.Duration
	31, // 34: bfd.v1.AddMicroBFDGroupRequest.required_min_rx_interval:type_name -> google.protobuf.Duration
	24, // 35: bfd.v1.AddMicroBFDGroupResponse.group:type_name -> bfd.v1.MicroBFDGroup
	24, // 36: bfd.v1.ListMicroBFDGroupsResponse.groups:type_name -> bfd.v1.MicroBFDGroup
	7,  // 37: bfd.v1.BfdService.AddSession:input_type -> bfd.v1.AddSessionRequest
	9,  // 38: bfd.v1.BfdService.DeleteSession:input_type -> bfd.v1.DeleteSessionRequest
	11, // 39: bfd.v1.BfdService.ListSessions:input_type -> bfd.v1.ListSessionsRequest
	13, // 40: bfd.v1.BfdService.GetSession:input_type -> bfd.v1.GetSessionRequest
	15, // 41: bfd.v1.BfdService.WatchSessionEvents:input_type -> bfd.v1.WatchSessionEventsRequest
	18, // 42: bfd.v1.EchoService.AddEchoSession:input_type -> bfd.v1.AddEchoSessionRequest
	20, // 43: bfd.v1.EchoService.DeleteEchoSession:input_type -> bfd.v1.DeleteEchoSessionRequest
	22, // 44: bfd.v1.EchoService.ListEchoSessions:input_type -> bfd.v1.ListEchoSessionsRequest
	25, // 45: bfd.v1.MicroBFDService.AddMicroBFDGroup:input_type -> bfd.v1.AddMicroBFDGroupRequest
	27, // 46: bfd.v1.MicroBFDService.DeleteMicroBFDGroup:input_type -> bfd.v1.DeleteMicroBFDGroupRequest
	29, // 47: bfd.v1.MicroBFDService.ListMicroBFDGroups:input_type -> bfd.v1.ListMicroBFDGroupsRequest
	8,  // 48: bfd.v1.BfdService.AddSession:output_type -> bfd.v1.AddSessionResponse
	10, // 49: bfd.v1.BfdService.DeleteSession:output_type -> bfd.v1.DeleteSessionResponse
	12, // 50: bfd.v1.BfdService.ListSessions:output_type -> bfd.v1.ListSessionsResponse
	14, // 51: bfd.v1.BfdService.GetSession:output_type -> bfd.v1.GetSessionResponse
	16, // 52: bfd.v1.BfdService.WatchSessionEvents:output_type -> bfd.v1.WatchSessionEventsResponse
	19, // 53: bfd.v1.EchoService.AddEchoSession:output_type -> bfd.v1.AddEchoSessionResponse
	21, // 54: bfd.v1.EchoService.DeleteEchoSession:output_type -> bfd.v1.DeleteEchoSessionResponse
	23, // 55: bfd.v1.EchoService.ListEchoSessions:output_type -> bfd.v1.ListEchoSessionsResponse
	26, // 56: bfd.v1.MicroBFDService.AddMicroBFDGroup:output_type -> bfd.v1.AddMicroBFDGroupResponse
	28, // 57: bfd.v1.MicroBFDService.DeleteMicroBFDGroup:output_type -> bfd.v1.DeleteMicroBFDGroupResponse
	30, // 58: bfd.v1.MicroBFDService.ListMicroBFDGroups:output_type -> bfd.v1.ListMicroBFDGroupsResponse
	48, // [48:59] is the sub-list for method output_type
	37, // [37:48] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_bfd_v1_bfd_proto_init() }
func file_bfd_v1_bfd_proto_init() {
	if File_bfd_v1_bfd_proto != nil {
		return
	}
	file_bfd_v1_bfd_proto_msgTypes[8].OneofWrappers = []any{
		(*GetSessionRequest_LocalDiscriminator)(nil),
		(*GetSessionRequest_PeerAddress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bfd_v1_bfd_proto_rawDesc), len(file_bfd_v1_bfd_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_bfd_v1_bfd_proto_goTypes,
		DependencyIndexes: file_bfd_v1_bfd_proto_depIdxs,
		EnumInfos:         file_bfd_v1_bfd_proto_enumTypes,
		MessageInfos:      file_bfd_v1_bfd_proto_msgTypes,
	}.Build()
	File_bfd_v1_bfd_proto = out.File
	file_bfd_v1_bfd_proto_goTypes = nil
	file_bfd_v1_bfd_proto_depIdxs = nil
}
