codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: true
  require_base: true

flags:
  unittests:
    paths:
      - "internal/"
      - "cmd/"
      - "pkg/"
    carryforward: true

ignore:
  - "pkg/bfdpb/**"
  - "test/**"
  - "deployments/**"
  - "docs/**"
