version: 2

builds:
  - id: gobfd
    main: ./cmd/gobfd
    binary: gobfd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dantte-lp/gobfd/internal/version.Version={{.Version}}
      - -X github.com/dantte-lp/gobfd/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/dantte-lp/gobfd/internal/version.BuildDate={{.Date}}

  - id: gobfdctl
    main: ./cmd/gobfdctl
    binary: gobfdctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dantte-lp/gobfd/internal/version.Version={{.Version}}
      - -X github.com/dantte-lp/gobfd/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/dantte-lp/gobfd/internal/version.BuildDate={{.Date}}

  - id: gobfd-haproxy-agent
    main: ./cmd/gobfd-haproxy-agent
    binary: gobfd-haproxy-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dantte-lp/gobfd/internal/version.Version={{.Version}}
      - -X github.com/dantte-lp/gobfd/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/dantte-lp/gobfd/internal/version.BuildDate={{.Date}}

  - id: gobfd-exabgp-bridge
    main: ./cmd/gobfd-exabgp-bridge
    binary: gobfd-exabgp-bridge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dantte-lp/gobfd/internal/version.Version={{.Version}}
      - -X github.com/dantte-lp/gobfd/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/dantte-lp/gobfd/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: configs/gobfd.example.yml
        dst: etc/gobfd/gobfd.example.yml
      - src: deployments/systemd/gobfd.service
        dst: lib/systemd/system/gobfd.service

checksum:
  name_template: checksums.txt

changelog:
  disable: true

nfpms:
  - id: packages
    package_name: gobfd
    vendor: dantte-lp
    homepage: https://github.com/dantte-lp/gobfd
    maintainer: dantte-lp
    description: BFD protocol daemon implementing RFC 5880/5881 for network failure detection.
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: configs/gobfd.example.yml
        dst: /etc/gobfd/gobfd.yml
        type: config|noreplace
      - src: deployments/systemd/gobfd.service
        dst: /lib/systemd/system/gobfd.service
    scripts:
      postinstall: deployments/nfpm/postinstall.sh
      preremove: deployments/nfpm/preremove.sh
    overrides:
      deb:
        dependencies:
          - systemd
      rpm:
        dependencies:
          - systemd

dockers:
  - image_templates:
      - "ghcr.io/dantte-lp/gobfd:{{ .Version }}"
      - "ghcr.io/dantte-lp/gobfd:latest"
    dockerfile: deployments/docker/Containerfile
    build_flag_templates:
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=GIT_COMMIT={{.ShortCommit}}"
      - "--build-arg=BUILD_DATE={{.Date}}"
