[project]
name = "gobfd-python-tools"
version = "0.0.0"
requires-python = "==3.14.7"
dependencies = []

[dependency-groups]
peer = []
runtime = []
quality = [
  "bandit==1.9.4",
  "codespell==2.4.3",
  "junit2html==31.1.4",
  "pip-audit==2.10.1",
  "ruff==0.16.4",
  "ty==0.0.74",
  "yamllint==1.38.0",
]

[tool.uv]
default-groups = []
package = false
required-version = "==0.12.6"

[tool.ruff]
line-length = 120
target-version = "py314"

[tool.ruff.lint]
ignore = ["COM812", "D203", "D213"]
select = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"test/interop-clab/vendor_images.py" = [
  "CPY001",
  "E501",
  "FBT001",
  "PERF401",
  "PLR0911",
  "PTH123",
  "TRY300",
]

[tool.ty.environment]
python-version = "3.14"

[tool.codespell]
ignore-words = ".codespell-ignore"
