// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bfd/v1/bfd.proto

package bfdv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dantte-lp/gobfd/pkg/bfdpb/bfd/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BfdServiceName is the fully-qualified name of the BfdService service.
	BfdServiceName = "bfd.v1.BfdService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BfdServiceAddSessionProcedure is the fully-qualified name of the BfdService's AddSession RPC.
	BfdServiceAddSessionProcedure = "/bfd.v1.BfdService/AddSession"
	// BfdServiceDeleteSessionProcedure is the fully-qualified name of the BfdService's DeleteSession
	// RPC.
	BfdServiceDeleteSessionProcedure = "/bfd.v1.BfdService/DeleteSession"
	// BfdServiceListSessionsProcedure is the fully-qualified name of the BfdService's ListSessions RPC.
	BfdServiceListSessionsProcedure = "/bfd.v1.BfdService/ListSessions"
	// BfdServiceGetSessionProcedure is the fully-qualified name of the BfdService's GetSession RPC.
	BfdServiceGetSessionProcedure = "/bfd.v1.BfdService/GetSession"
	// BfdServiceWatchSessionEventsProcedure is the fully-qualified name of the BfdService's
	// WatchSessionEvents RPC.
	BfdServiceWatchSessionEventsProcedure = "/bfd.v1.BfdService/WatchSessionEvents"
)

// BfdServiceClient is a client for the bfd.v1.BfdService service.
type BfdServiceClient interface {
	// AddSession creates a new BFD session with the given parameters.
	AddSession(context.Context, *v1.AddSessionRequest) (*v1.AddSessionResponse, error)
	// DeleteSession removes a BFD session by its local discriminator.
	DeleteSession(context.Context, *v1.DeleteSessionRequest) (*v1.DeleteSessionResponse, error)
	// ListSessions returns all active BFD sessions.
	ListSessions(context.Context, *v1.ListSessionsRequest) (*v1.ListSessionsResponse, error)
	// GetSession returns a single session by discriminator or peer address.
	GetSession(context.Context, *v1.GetSessionRequest) (*v1.GetSessionResponse, error)
	// WatchSessionEvents streams BFD session state changes (server-side streaming).
	WatchSessionEvents(context.Context, *v1.WatchSessionEventsRequest) (*connect.ServerStreamForClient[v1.WatchSessionEventsResponse], error)
}

// NewBfdServiceClient constructs a client for the bfd.v1.BfdService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBfdServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BfdServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bfdServiceMethods := v1.File_bfd_v1_bfd_proto.Services().ByName("BfdService").Methods()
	return &bfdServiceClient{
		addSession: connect.NewClient[v1.AddSessionRequest, v1.AddSessionResponse](
			httpClient,
			baseURL+BfdServiceAddSessionProcedure,
			connect.WithSchema(bfdServiceMethods.ByName("AddSession")),
			connect.WithClientOptions(opts...),
		),
		deleteSession: connect.NewClient[v1.DeleteSessionRequest, v1.DeleteSessionResponse](
			httpClient,
			baseURL+BfdServiceDeleteSessionProcedure,
			connect.WithSchema(bfdServiceMethods.ByName("DeleteSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+BfdServiceListSessionsProcedure,
			connect.WithSchema(bfdServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v1.GetSessionRequest, v1.GetSessionResponse](
			httpClient,
			baseURL+BfdServiceGetSessionProcedure,
			connect.WithSchema(bfdServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		watchSessionEvents: connect.NewClient[v1.WatchSessionEventsRequest, v1.WatchSessionEventsResponse](
			httpClient,
			baseURL+BfdServiceWatchSessionEventsProcedure,
			connect.WithSchema(bfdServiceMethods.ByName("WatchSessionEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bfdServiceClient implements BfdServiceClient.
type bfdServiceClient struct {
	addSession         *connect.Client[v1.AddSessionRequest, v1.AddSessionResponse]
	deleteSession      *connect.Client[v1.DeleteSessionRequest, v1.DeleteSessionResponse]
	listSessions       *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	getSession         *connect.Client[v1.GetSessionRequest, v1.GetSessionResponse]
	watchSessionEvents *connect.Client[v1.WatchSessionEventsRequest, v1.WatchSessionEventsResponse]
}

// AddSession calls bfd.v1.BfdService.AddSession.
func (c *bfdServiceClient) AddSession(ctx context.Context, req *v1.AddSessionRequest) (*v1.AddSessionResponse, error) {
	response, err := c.addSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteSession calls bfd.v1.BfdService.DeleteSession.
func (c *bfdServiceClient) DeleteSession(ctx context.Context, req *v1.DeleteSessionRequest) (*v1.DeleteSessionResponse, error) {
	response, err := c.deleteSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListSessions calls bfd.v1.BfdService.ListSessions.
func (c *bfdServiceClient) ListSessions(ctx context.Context, req *v1.ListSessionsRequest) (*v1.ListSessionsResponse, error) {
	response, err := c.listSessions.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetSession calls bfd.v1.BfdService.GetSession.
func (c *bfdServiceClient) GetSession(ctx context.Context, req *v1.GetSessionRequest) (*v1.GetSessionResponse, error) {
	response, err := c.getSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// WatchSessionEvents calls bfd.v1.BfdService.WatchSessionEvents.
func (c *bfdServiceClient) WatchSessionEvents(ctx context.Context, req *v1.WatchSessionEventsRequest) (*connect.ServerStreamForClient[v1.WatchSessionEventsResponse], error) {
	return c.watchSessionEvents.CallServerStream(ctx, connect.NewRequest(req))
}

// BfdServiceHandler is an implementation of the bfd.v1.BfdService service.
type BfdServiceHandler interface {
	// AddSession creates a new BFD session with the given parameters.
	AddSession(context.Context, *v1.AddSessionRequest) (*v1.AddSessionResponse, error)
	// DeleteSession removes a BFD session by its local discriminator.
	DeleteSession(context.Context, *v1.DeleteSessionRequest) (*v1.DeleteSessionResponse, error)
	// ListSessions returns all active BFD sessions.
	ListSessions(context.Context, *v1.ListSessionsRequest) (*v1.ListSessionsResponse, error)
	// GetSession returns a single session by discriminator or peer address.
	GetSession(context.Context, *v1.GetSessionRequest) (*v1.GetSessionResponse, error)
	// WatchSessionEvents streams BFD session state changes (server-side streaming).
	WatchSessionEvents(context.Context, *v1.WatchSessionEventsRequest, *connect.ServerStream[v1.WatchSessionEventsResponse]) error
}

// NewBfdServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBfdServiceHandler(svc BfdServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bfdServiceMethods := v1.File_bfd_v1_bfd_proto.Services().ByName("BfdService").Methods()
	bfdServiceAddSessionHandler := connect.NewUnaryHandlerSimple(
		BfdServiceAddSessionProcedure,
		svc.AddSession,
		connect.WithSchema(bfdServiceMethods.ByName("AddSession")),
		connect.WithHandlerOptions(opts...),
	)
	bfdServiceDeleteSessionHandler := connect.NewUnaryHandlerSimple(
		BfdServiceDeleteSessionProcedure,
		svc.DeleteSession,
		connect.WithSchema(bfdServiceMethods.ByName("DeleteSession")),
		connect.WithHandlerOptions(opts...),
	)
	bfdServiceListSessionsHandler := connect.NewUnaryHandlerSimple(
		BfdServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(bfdServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	bfdServiceGetSessionHandler := connect.NewUnaryHandlerSimple(
		BfdServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(bfdServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	bfdServiceWatchSessionEventsHandler := connect.NewServerStreamHandlerSimple(
		BfdServiceWatchSessionEventsProcedure,
		svc.WatchSessionEvents,
		connect.WithSchema(bfdServiceMethods.ByName("WatchSessionEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bfd.v1.BfdService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BfdServiceAddSessionProcedure:
			bfdServiceAddSessionHandler.ServeHTTP(w, r)
		case BfdServiceDeleteSessionProcedure:
			bfdServiceDeleteSessionHandler.ServeHTTP(w, r)
		case BfdServiceListSessionsProcedure:
			bfdServiceListSessionsHandler.ServeHTTP(w, r)
		case BfdServiceGetSessionProcedure:
			bfdServiceGetSessionHandler.ServeHTTP(w, r)
		case BfdServiceWatchSessionEventsProcedure:
			bfdServiceWatchSessionEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBfdServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBfdServiceHandler struct{}

func (UnimplementedBfdServiceHandler) AddSession(context.Context, *v1.AddSessionRequest) (*v1.AddSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bfd.v1.BfdService.AddSession is not implemented"))
}

func (UnimplementedBfdServiceHandler) DeleteSession(context.Context, *v1.DeleteSessionRequest) (*v1.DeleteSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bfd.v1.BfdService.DeleteSession is not implemented"))
}

func (UnimplementedBfdServiceHandler) ListSessions(context.Context, *v1.ListSessionsRequest) (*v1.ListSessionsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bfd.v1.BfdService.ListSessions is not implemented"))
}

func (UnimplementedBfdServiceHandler) GetSession(context.Context, *v1.GetSessionRequest) (*v1.GetSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bfd.v1.BfdService.GetSession is not implemented"))
}

func (UnimplementedBfdServiceHandler) WatchSessionEvents(context.Context, *v1.WatchSessionEventsRequest, *connect.ServerStream[v1.WatchSessionEventsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("bfd.v1.BfdService.WatchSessionEvents is not implemented"))
}
