FROM docker.io/library/golang:1.27.1-trixie@sha256:9baa6b4187bbb98d240372a8a235ac0bb6b5ddd52bba1431dc2f7c0705862728 AS builder

RUN groupadd -r gobfd && useradd -r -g gobfd -s /sbin/nologin gobfd

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .

ARG VERSION=dev
ARG GIT_COMMIT=unknown
ARG BUILD_DATE=unknown
RUN CGO_ENABLED=0 go build -trimpath \
    -ldflags="-s -w \
      -X github.com/dantte-lp/gobfd/internal/version.Version=${VERSION} \
      -X github.com/dantte-lp/gobfd/internal/version.GitCommit=${GIT_COMMIT} \
      -X github.com/dantte-lp/gobfd/internal/version.BuildDate=${BUILD_DATE}" \
    -o /bin/gobfd ./cmd/gobfd
RUN CGO_ENABLED=0 go build -trimpath \
    -ldflags="-s -w \
      -X github.com/dantte-lp/gobfd/internal/version.Version=${VERSION} \
      -X github.com/dantte-lp/gobfd/internal/version.GitCommit=${GIT_COMMIT} \
      -X github.com/dantte-lp/gobfd/internal/version.BuildDate=${BUILD_DATE}" \
    -o /bin/gobfdctl ./cmd/gobfdctl

FROM docker.io/library/debian:trixie-slim@sha256:d7e12182ce18b85b93007c1dedf31f2d29e01ccf3182cc4017c709b6259bc132 AS production

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /bin/gobfd /bin/gobfdctl /bin/

USER gobfd:gobfd

ENV GOMEMLIMIT=256MiB

EXPOSE 3784/udp 4784/udp 50051

ENTRYPOINT ["/bin/gobfd"]
